insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451003, 'DIRETORIA DE TRANSPORTES E SERVICOS GERAIS/CAMG', 'DIRETORIA DE TRANSPORTES E SERVICOS', '01ª RISP – Belo Horizonte', 'BELO HORIZONTE');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451005, 'ALMOXARIFADO CENTRAL/SEAP', 'ALMOXARIFADO/SEAP', '03ª RISP – Vespasiano', 'VESPASIANO');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451006, 'ANEXO JOSE DE ALENCAR ROGEDO/', 'AJAR- ANEXO JOSE DE ALENCAR ROGEDO', '04ª RISP – Juiz de Fora', 'JUIZ DE FORA');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451008, 'PENITENCIARIA JOSE EDSON CAVALIERI', 'PJEC-PENITENCIARIA JOSE EDSON CAVALIERI', '04ª RISP – Juiz de Fora', 'JUIZ DE FORA');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451010, 'CASA DO ALBERGADO PRESIDENTE JOAO PESSOA', 'CAPJP- CASA DO ALBERGADO_JOAO PESSOA', '01ª RISP – Belo Horizonte', 'BELO HORIZONTE');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451012, 'COMPLEXO PENITENCIARIO FEMININO ESTEVAO PINTO', 'CPFEP- PENIT. FEMININO ESTEVAO PINTO', '01ª RISP – Belo Horizonte', 'BELO HORIZONTE');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451014, 'PENITENCIARIA FRANCISCO FLORIANO DE PAULA', 'PFFP- PENIT. FRANCISCO FLORIANO DE PAULA', '08ª RISP – Governador Valadares', 'GOVERNADOR VALADARES');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451017, 'HOSPITAL PSIQUIATRICO E JUDICIARIO JORGE VAZ', 'HPJJV-HOSPITAL PSIQUIATRICO JORGE VAZ', '13ª RISP – Barbacena', 'BARBACENA');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451019, 'HOSPITAL DE TOXICOMANOS PADRE WILSON VALE DA COSTA', 'HOSP.TOXICOMANOS PE WILSON VALE DA COSTA', '04ª RISP – Juiz de Fora', 'JUIZ DE FORA');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451021, 'PENITENCIARIA AGOSTINHO DE OLIVEIRA JUNIOR', 'PAOJ-PENIT.AGOSTINHO DE OLIVEIRA JUNIOR', '16ª RISP – Unaí', 'UNAI');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451023, 'PRESIDIO JOSE ABRANCHES GONCALVES', 'PRESIDIO JOSE ABRANCHES GONCALVES', '02ª RISP – Contagem', 'RIBEIRAO DAS NEVES');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451025, 'COMPLEXO PENITENCIARIO NELSON HUNGRIA', 'COMPLEXO PENITENCIARIO NELSON HUNGRIA', '02ª RISP – Contagem', 'CONTAGEM');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451027, 'COMPLEXO PENITENCIARIO NOSSA SENHORA DO CARMO', 'COMPLEXO PENIT. NOSSA SENHORA DO CARMO', '10ª RISP – Patos de Minas', 'CARMO DO PARANAIBA');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451029, 'PENITENCIARIA DE TEOFILO OTONI', 'PENITENCIARIA DE TEOFILO OTONI', '15ª RISP – Teófilo Otoni', 'TEOFILO OTONI');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451031, 'PRESIDIO FLORAMAR', 'PRESIDIO FLORAMAR', '07ª RISP – Divinópolis', 'DIVINOPOLIS');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451033, 'PRESIDIO PROFESSOR JACY DE ASSIS', 'PRESIDIO PROFESSOR JACY DE ASSIS', '09ª RISP – Uberlândia', 'UBERLANDIA');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451035, 'PRESIDIO SEBASTIAO SATIRO', 'PRSS-PRESIDIO SEBASTIAO SATIRO', '10ª RISP – Patos de Minas', 'PATOS DE MINAS');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451037, 'PRESIDIO ANTONIO DUTRA LADEIRA', 'PRESIDIO ANTONIO DUTRA LADEIRA', '02ª RISP – Contagem', 'RIBEIRAO DAS NEVES');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451039, 'PENITENCIARIA DENIO MOREIRA DE CARVALHO', 'PENITENCIARIA DENIO MOREIRA DE CARVALHO', '12ª RISP – Ipatinga', 'IPABA');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451041, 'PENITENCIARIA JOSE MARIA ALKIMIM', 'PENITENCIARIA JOSE MARIA ALKIMIN', '02ª RISP – Contagem', 'RIBEIRAO DAS NEVES');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451043, 'PRESIDIO DORES DO INDAIA', 'PRESIDIO DORES DO INDAIA', '07ª RISP – Divinópolis', 'DORES DO INDAIA');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451045, 'NUCLEO DE PATRIMONIO-CADASTRO DE BENS PERMANENTES', 'NUCLEO DE PATRIMONIO/CADASTRO DE BENS', '01ª RISP – Belo Horizonte', 'BELO HORIZONTE');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451046, 'PRESIDIO SANTA MARIA DO SUACUI', 'PRESIDIO SANTA MARIA DO SUACUI', '08ª RISP – Governador Valadares', 'SANTA MARIA DO SUACUI');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451052, 'PRESIDIO DE RESPLENDOR', 'PRESIDIO DE RESPLENDOR', '08ª RISP – Governador Valadares', 'RESPLENDOR');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451065, 'SUPERINTENDENCIA DE ARTICULACAO INSTITUCIONAL E GESTAO DE VAGAS', 'SAIGV/SEDS', '01ª RISP – Belo Horizonte', 'BELO HORIZONTE');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451066, 'PRESIDIO RIO PARDO DE MINAS', 'PRESIDIO RIO PARDO DE MINAS', '11ª RISP – Montes Claros', 'RIO PARDO DE MINAS');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451068, 'COORDENADORIA DE INFORMACAO E INTELIGENCIA', 'CII/SEAP', '01ª RISP – Belo Horizonte', 'BELO HORIZONTE');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451070, 'SUPERINTENDENCIA DE TECNOLOGIA INFORMACAO COMUNICACAO', 'SUPERINTENDENCIA T.I.COMUNICACAO', '01ª RISP – Belo Horizonte', 'BELO HORIZONTE');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451071, 'PENITENCIARIA REGIONAL PROFESSOR JASON SOARES ALBERGARIA', 'PENIT. PROF. JASON SOARES ALBERGARIA', '02ª RISP – Contagem', 'SAO JOAQUIM DE BICAS');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451072, 'COMPLEXO PENITENCIARIO DOUTOR PIO CANEDO', 'COMPLEXO PENITENCIARIO DOUTOR PIO CANEDO', '07ª RISP – Divinópolis', 'PARA DE MINAS');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451075, 'PRESIDIO DO SERRO', 'PRESIDIO DO SERRO', '14ª RISP – Curvelo', 'SERRO');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451078, 'DELEG. DE ORIENTACAO PROTECAO A CRIANCA E AO ADOLESCENTES', 'DOPCAD SANTA LUZIA', 'SOCIOEDUCATIVO', 'SANTA LUZIA');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451079, 'DIRETORIA DE RECURSOS TECNOLOGICOS', 'DRT-DIRETORIA DE RECURSOS TECNOLOGICOS', '01ª RISP – Belo Horizonte', 'BELO HORIZONTE');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451085, 'GABINETE', 'GABINETE', '01ª RISP – Belo Horizonte', 'BELO HORIZONTE');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451089, 'DIRETORIA DE SISTEMAS DE INFORMACAO', 'DIRETORIA DE SISTEMAS DE INFORMACAO', '01ª RISP – Belo Horizonte', 'BELO HORIZONTE');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451091, 'PENITENCIARIA PROFESSOR JOAO PIMENTA DA VEIGA', 'PENITENCIARIA JOSE PIMENTA DA VEIGA', '09ª RISP – Uberlândia', 'UBERLANDIA');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451093, 'CENTRO DE APOIO MEDICO E PERICIAL', 'CAMP', '02ª RISP – Contagem', 'RIBEIRAO DAS NEVES');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451094, 'ACADEMIA DO SISTEMA PRISIONAL', 'ACADEMIA DO SISTEMA PRISIONAL', '02ª RISP – Contagem', 'RIBEIRAO DAS NEVES');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451096, 'CENTRO SOCIOEDUCATIVO PIRAPORA', 'CSEPIRAPORA', 'SOCIOEDUCATIVO', 'PIRAPORA');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451097, 'DEPARTAMENTO PENITENCIARIO DE MINAS GERAIS', 'DEPEN/MG', '01ª RISP – Belo Horizonte', 'BELO HORIZONTE');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451100, 'COMANDO DE OPERACOES ESPECIAIS', 'COPE', '01ª RISP – Belo Horizonte', 'BELO HORIZONTE');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451107, 'CENTRO SOCIOEDUCATIVO MONTES CLAROS', 'CSE MONTES CLAROS', 'SOCIOEDUCATIVO', 'MONTES CLAROS');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451108, 'DIRETORIA DE TRABALHO E PRODUCAO', 'DIRETORIA DE TRABALHO E PRODUCAO', '01ª RISP – Belo Horizonte', 'BELO HORIZONTE');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451109, 'CORREGEDORIA', 'CORREGEDORIA', '01ª RISP – Belo Horizonte', 'BELO HORIZONTE');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451111, 'PRESIDIO DE NOVA SERRANA', 'PRESIDIO DE NOVA SERRANA', '07ª RISP – Divinópolis', 'NOVA SERRANA');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451116, 'PRESIDIO DE ARAGUARI', 'PRESIDIO DE ARAGUARI', '09ª RISP – Uberlândia', 'ARAGUARI');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451119, 'PENITENCIARIA PROFESSOR ARIOSVALDO CAMPOS PIRES', 'PENIT. PROF. ARIOSVALDO CAMPOS PIRES', '04ª RISP – Juiz de Fora', 'JUIZ DE FORA');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451125, 'PENITENCIARIA DE FRANCISCO SA', 'PENITENCIARIDE FRANCISCO SA', '11ª RISP – Montes Claros', 'FRANCISCO SA');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451128, 'PRESIDIO DE SAO JOAQUIM DE BICAS_I', 'PRESIDIO DE SAO JOAQUIM DE BICAS I', '02ª RISP – Contagem', 'SAO JOAQUIM DE BICAS');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451129, 'CERESP GAMELEIRA(CENTRO DE REMANEJAMENTO PRISIONA L DE BH)', 'CERESP-GAMELEIRA', '01ª RISP – Belo Horizonte', 'BELO HORIZONTE');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451130, 'PRESIDIO DOUTOR CARLOS VITORIANO', 'PRESID.DOUTOR CARLOS VITORIANO-ARACAUAI', '15ª RISP – Teófilo Otoni', 'ARACUAI');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451133, 'PRESIDIO DE VICOSA', 'PRESIDIO DE VICOSA', '04ª RISP – Juiz de Fora', 'VICOSA');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451137, 'CENTRO SOCIOEDUCATIVO UBERLANDIA', 'CSE UBERLANDIA', 'SOCIOEDUCATIVO', 'UBERLANDIA');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451138, 'PRESIDIO DE ITAMOGI', 'PRESIDIO DE ITAMOGI', '18ª RISP – Poços de Caldas', 'ITAMOGI');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451140, 'ALMOXARIFADO CENTRAL- UNIDADE USUARIA/CONSUMO', 'ALMOXARIFADO- UNIDADE DE CONSUMO/USUARIA', '03ª RISP – Vespasiano', 'VESPASIANO');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451147, 'CENTRO DE INTERNACAO PROVISORIA SAO BENEDITO', 'CEIP SAOBENEDITO', 'SOCIOEDUCATIVO', 'BELO HORIZONTE');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451152, 'PRESIDIO INSPETOR JOSE MARTINHO DRUMOND', 'PRESIDIO INSPETOR JOSE MARTINHO DRUMOND', '02ª RISP – Contagem', 'RIBEIRAO DAS NEVES');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451153, 'PENITENCIARIA PROFESSOR ALUIZIO IGNACIO DE OLIVEIRA', 'PPAIO', '05ª RISP – Uberaba', 'UBERABA');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451154, 'PENITENCIARIA DE TRES CORACOES', 'PENITENCIARIA DE TRES CORACOES', '06ª RISP – Lavras', 'TRES CORACOES');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451155, 'PENITENCIARIA DEPUTADO EXPEDITO DE FARIA TAVARES', 'PENIT. DEPUTADO EXPEDITO FARIA TAVARES', '10ª RISP – Patos de Minas', 'PATROCINIO');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451156, 'PENITENCIARIA DOUTOR MANOEL MARTINS LISBOA JUNIOR', 'PENIT.DR MANOEL MARTINS LISBOA JUNIOR', '04ª RISP – Juiz de Fora', 'MURIAE');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451157, 'PRESIDIO DE VESPASIANO', 'PRESIDIO DE VESPASIANO', '03ª RISP – Vespasiano', 'VESPASIANO');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451161, 'CENTRO SOCIOEDUCATIVO SANTA HELENA', 'CSE SANTA HELENA', 'SOCIOEDUCATIVO', 'BELO HORIZONTE');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451162, 'CENTRO SOCIOEDUCATIVO UNAI', 'CSE UNAI', 'SOCIOEDUCATIVO', 'UNAI');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451163, 'CENTRO SOCIEDUCATIVO LINDEIA', 'CSE LINDEIA', 'SOCIOEDUCATIVO', 'BELO HORIZONTE');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451165, 'CENTRO SOCIOEDUCATIVO TEOFILO OTONI', 'CSE TEOFILO OTONI', 'SOCIOEDUCATIVO', 'TEOFILO OTONI');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451166, 'SUPERINTENDENCIA DE HUMANIZACAO DO ATENDIMENTO', 'SUPE.DE HUMANIZACAO DO ATENDIMENTO', '01ª RISP – Belo Horizonte', 'BELO HORIZONTE');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451171, 'CENTRO SOCIOEDUCATIVO SAO JERONIMO', 'CSE SAO JERONIMO', 'SOCIOEDUCATIVO', 'BELO HORIZONTE');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451172, 'CENTRO SOCIOEDUCATIVO DE SETE LAGOAS', 'CSE SETE LAGOAS', 'SOCIOEDUCATIVO', 'SETE LAGOAS');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451181, 'PRESIDIO DE GOVERNADOR VALADARES', 'PRESIDIO GOV.VALADARES', '08ª RISP – Governador Valadares', 'GOVERNADOR VALADARES');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451183, 'PRESIDIO DE ELOI MENDES', 'PRESIDIO DE ELOI MENDES', '06ª RISP – Lavras', 'ELOI MENDES');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451190, 'PRESIDIO DE SAO DOMINGOS DO PRATA', 'PRESIDIO DE SAO DOMINGOS DO PRATA', '12ª RISP – Ipatinga', 'SAO DOMINGOS DO PRATA');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451191, 'DIRETORIA DE SUPORTE E INFRAESTRUTURA/INFRAESTRUTURA ALMOX', 'DSU-INFRA', '03ª RISP – Vespasiano', 'VESPASIANO');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451192, 'SUPERINTENDENCIA DE SEGURANCA PRISIONAL', 'SSEG/SUSEP/SEAP', '01ª RISP – Belo Horizonte', 'BELO HORIZONTE');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451195, 'PRESÍDIO PROMOTOR JOSÉ COSTA', 'PRESIDIO DE SETE LAGOAS', '19ª RISP - Sete Lagoas', 'SETE LAGOAS');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451198, 'CENTRO SOCIOEDUCATIVO ANDRADAS', 'CSE ANDRADAS', 'SOCIOEDUCATIVO', 'BELO HORIZONTE');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451200, 'PRESIDIO DE PEDRO LEOPOLDO', 'PRESIDIO PEDRO LEOPOLDO', '19ª RISP - Sete Lagoas', 'PEDRO LEOPOLDO');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451202, 'DELEGACIA DE ORIENTACAO PROTECAO A CRIANCA E AO ADOLESCENTES', 'DOPCAD CONTAGEM', 'SOCIOEDUCATIVO', 'CONTAGEM');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451206, 'PRESIDIO DE CORONEL FABRICIANO', 'PRESIDIO DE CORONEL FABRICIANO', '12ª RISP – Ipatinga', 'CORONEL FABRICIANO');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451207, 'PENITENCIARIA DE FORMIGA', 'PENITENCIARIA DE FORMIGA/SEDS', '07ª RISP – Divinópolis', 'FORMIGA');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451208, 'PRESIDIO DE CARATINGA', 'PRESIDIO DE CARATINGA', '12ª RISP – Ipatinga', 'CARATINGA');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451209, 'PRESIDIO DE JOAO PINHEIRO', 'PRESIDIO DE JOAO PINHEIRO/SEDS', '16ª RISP – Unaí', 'JOAO PINHEIRO');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451210, 'PRESIDIO DE ANDRADAS', 'PRESIDIO DE ANDRADAS/SEDS', '18ª RISP – Poços de Caldas', 'ANDRADAS');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451211, 'PRESIDIO DE MONTE CARMELO', 'PRESIDIO DE MONTE CARMELO/SEDS', '10ª RISP – Patos de Minas', 'MONTE CARMELO');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451212, 'PRESIDIO DO CARMO DO RIO CLARO', 'PRESIDIO DO CARMO DO RIO CLARO', '18ª RISP – Poços de Caldas', 'CARMO DO RIO CLARO');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451219, 'PRESIDIO DE ARAXA', 'PRESIDIO DE ARAXA', '05ª RISP – Uberaba', 'ARAXA');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451220, 'PRESIDIO DE UNAI', 'PRESIDIO DE UNAI', '16ª RISP – Unaí', 'UNAI');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451221, 'PRESIDIO DE TEOFILO OTONI', 'PRESIDIO DE TEOFILO OTONI/SEDS', '15ª RISP – Teófilo Otoni', 'TEOFILO OTONI');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451222, 'CERESP BETIM', 'CERESP-BETIM', '02ª RISP – Contagem', 'BETIM');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451228, 'DIRETORIA DE SUPORTE E INFRAESTRUTURA', 'DIRETORIA DE SUPORTE E INFRAESTRUTURA', '01ª RISP – Belo Horizonte', 'BELO HORIZONTE');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451229, 'PRESIDIO DE SAO LOURENCO', 'PRESIDIO DE SAO LOURENCO', '17ª RISP – Pouso Alegre', 'SAO LOURENCO');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451233, 'SUPERINTENDENCIA DE INTELIGENCIA E INTEGRACAO DA INFORMACAO', 'SIII', 'SOCIOEDUCATIVO', 'BELO HORIZONTE');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451240, 'PRESIDIO DE SAO JOAO DEL REY/SEDS', 'PRESIDIO SAO JOAO DEL REY/SEDS', '13ª RISP – Barbacena', 'SAO JOAO DEL REI');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451242, 'CENTRAL DE SUPRIMENTOS DA SSP', 'CS/SSP', '01ª RISP – Belo Horizonte', 'BELO HORIZONTE');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451244, 'SUBSECRETARIA DE INOVACAO E LOGISTICA E TECNOLOGIA DO SISTEMA DE ADMINISTRACAO PRISIONAL', 'SULOT', '01ª RISP – Belo Horizonte', 'BELO HORIZONTE');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451246, 'CENTRO SOCIOEDUCATIVO SANTA TEREZINHA', 'CSE SANTA TEREZINHA', 'SOCIOEDUCATIVO', 'BELO HORIZONTE');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451247, 'CENTRO DE INTERNACAO DOM BOSCO', 'CEIP DOM BOSCO', 'SOCIOEDUCATIVO', 'BELO HORIZONTE');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451251, 'CENTRO SOCIOEDUCATIVO SAO FRANSCISCO', 'CSE SAO FRANSCISCO', 'SOCIOEDUCATIVO', 'GOVERNADOR VALADARES');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451252, '4 DIRETORIA REGIONAL DE ADMINISTRACAO PRISIONAL', '4 DRAP/SEAP', '04ª RISP – Juiz de Fora', 'JUIZ DE FORA');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451257, 'SUBSECRETARIA DE INTELIGENCIA E ATUACAO INTEGRADA', 'SUB.INTELIGENCIA E ATUACAO INTEGRADA', 'SOCIOEDUCATIVO', 'BELO HORIZONTE');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451262, 'CENTRO SOCIOEDUCATIVO UBERABA', 'CENTRO SOCIOEDUCATIVO UBERABA', 'SOCIOEDUCATIVO', 'UBERABA');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451264, 'SUPERINTENDENCIA DE INTEGRACAO E PLANEJAMENTO OPERACIONAL', 'SIPO', 'SOCIOEDUCATIVO', 'BELO HORIZONTE');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451270, 'SUBSECRETARIA DE PREVENCAO A CRIMINALIDADE', 'SUB.PREVENCAO A CRIMINALIDADE', 'SOCIOEDUCATIVO', 'BELO HORIZONTE');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451271, 'PRESIDIO REGIONAL DE MONTES CLAROS', 'PRESIDIO REGIONAL DE MONTES CLAROS', '11ª RISP – Montes Claros', 'MONTES CLAROS');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451274, 'CERESP IPATINGA', 'CERESP IPATINGA', '12ª RISP – Ipatinga', 'IPATINGA');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451277, 'CENTRO DE REMANEJAMENTO DO SISTEMA PRISIONAL JUIZ DE FORA', 'CERESP JUIZ DE FORA', '04ª RISP – Juiz de Fora', 'JUIZ DE FORA');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451279, 'PRESIDIO DE LAVRAS', 'PRESIDIO DE LAVRAS', '06ª RISP – Lavras', 'LAVRAS');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451281, 'PRESIDIO DE COROMANDEL', 'PRESIDIO DE COROMANDEL/SEDS', '10ª RISP – Patos de Minas', 'COROMANDEL');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451283, 'PRESIDIO DE SAO SEBASTIAO DO PARAISO', 'PRESIDIO S. SEBASTIAO DO PARAISO/SEDS', '18ª RISP – Poços de Caldas', 'SAO SEBASTIAO DO PARAISO');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451285, 'PRESIDIO DE PASSOS', 'PRESIDIO DE PASSOS', '18ª RISP – Poços de Caldas', 'PASSOS');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451287, 'PRESIDIO DE GUARANESIA', 'PRESIDIO DE GUARANESIA/SEDS', '18ª RISP – Poços de Caldas', 'GUARANESIA');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451289, 'PRESIDIO DE PIUMHI', 'PRESIDIO DE PIUMHI', '18ª RISP – Poços de Caldas', 'PIUMHI');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451291, 'PRESIDIO DE ALVORADA - MOC', 'PRESIDIO DE ALVORADA/SEDS', '11ª RISP – Montes Claros', 'MONTES CLAROS');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451296, 'DIRETORIA DE SEGURANCA EXTERNA', 'DIRETORIA DE SEGURANCA EXTERNA', '01ª RISP – Belo Horizonte', 'BELO HORIZONTE');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451298, 'PRESIDIO DE PRESIDENTE OLEGARIO', 'PRESIDIO PRESIDENTE OLEGARIO', '10ª RISP – Patos de Minas', 'PRESIDENTE OLEGARIO');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451300, 'PRESIDIO DE CAXAMBU', 'PRESíDIO DE CAXAMBU', '17ª RISP – Pouso Alegre', 'CAXAMBU');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451302, 'PRESIDIO DE PONTE NOVA', 'PRESIDIO DE PONTE NOVA/SEDS', '12ª RISP – Ipatinga', 'PONTE NOVA');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451304, 'PRESIDIO DE JOAO MONLEVADE', 'PRESIDIO JOAO MONLEVADE', '12ª RISP – Ipatinga', 'JOAO MONLEVADE');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451306, 'PRESIDIO DE CURVELO', 'PRESIDIO DE CURVELO/SEDS', '14ª RISP – Curvelo', 'CURVELO');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451308, 'PRESIDIO DE BARBACENA', 'PRESIDIO DE BARBACENA/SEDS', '13ª RISP – Barbacena', 'BARBACENA');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451310, 'PRESIDIO DE CONSELHEIRO LAFAIETE', 'PRESIDIO DE CONSELHEIRO LAFAIETE', '13ª RISP – Barbacena', 'CONSELHEIRO LAFAIETE');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451312, 'PRESIDIO DE OURO PRETO', 'PRESIDIO DE OURO PRETO', '03ª RISP – Vespasiano', 'OURO PRETO');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451314, 'PRESIDIO DE VISCONDE DO RIO BRANCO', 'PRESIDIO DE VISCONDE DO RIO BRANCO', '04ª RISP – Juiz de Fora', 'VISCONDE DO RIO BRANCO');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451316, 'PRESIDIO DE VARGINHA', 'PRESIDIO DE VARGINHA', '06ª RISP – Lavras', 'VARGINHA');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451318, 'PRESIDIO DE ITUIUTABA', 'PRESIDIO DE ITUIUTABA', '09ª RISP – Uberlândia', 'ITUIUTABA');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451320, 'PRESIDIO DE MURIAE', 'PRESIDIO DE MURIAE', '04ª RISP – Juiz de Fora', 'MURIAE');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451322, 'PRESIDIO DE POCOS DE CALDAS', 'PRESIDIO DE POCOS DE CALDAS/SEDS', '18ª RISP – Poços de Caldas', 'POCOS DE CALDAS');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451324, 'PRESIDIO DE PARACATU', 'PRESIDIO DE PARACATU', '16ª RISP – Unaí', 'PARACATU');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451326, 'PRESIDIO DE UBA', 'PRESIDIO DE UBA', '04ª RISP – Juiz de Fora', 'UBA');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451328, 'PRESIDIO DE ALFENAS', 'PRESIDIO DE ALFENAS', '18ª RISP – Poços de Caldas', 'ALFENAS');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451330, 'PRESIDIO DE ITABIRA', 'PRESIDIO DE ITABIRA', '12ª RISP – Ipatinga', 'ITABIRA');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451332, 'COMPLEXO PENITENCIARIO DE PONTE NOVA', 'PENITENCIARIA PONTE NOVA', '12ª RISP – Ipatinga', 'PONTE NOVA');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451334, 'PRESIDIO DE ITAJUBA', 'PRESIDIO DE ITAJUBA', '17ª RISP – Pouso Alegre', 'ITAJUBA');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451336, 'PRESIDIO DE SANTA LUZIA', 'PRESIDIO DE SANTA LUZIA', '03ª RISP – Vespasiano', 'SANTA LUZIA');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451339, 'PRESIDIO DE OLIVEIRA-DOUTOR NELSON PIRES', 'PRESIDIO DE OLIVEIRA', '06ª RISP – Lavras', 'OLIVEIRA');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451341, 'PRESIDIO DA RMBHII - BICAS', 'PRESIDIO DA RMBH II - BICAS/ SEDS', '02ª RISP – Contagem', 'SAO JOAQUIM DE BICAS');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451343, 'PRESIDIO DE POUSO ALEGRE', 'PRESIDIO DE POUSO ALEGRE', '17ª RISP – Pouso Alegre', 'POUSO ALEGRE');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451347, 'PRESIDIO DE ITAOBIM', 'PRESIDIO ITAOBIM', '15ª RISP – Teófilo Otoni', 'ITAOBIM');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451349, 'CENTRO DE REFERENCIA A GESTANTES DO SISTEMA PRISIONAL', 'CRGPL- CENTRO DE REFERENCIA A GESTANTES', '03ª RISP – Vespasiano', 'VESPASIANO');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451351, 'CERESP CONTAGEM', 'CERESP - CONTAGEM', '02ª RISP – Contagem', 'CONTAGEM');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451371, 'PRESIDIO NOVA ERA', 'PRESIDIO NOVA ERA', '12ª RISP – Ipatinga', 'NOVA ERA');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451374, 'SUBSECRETARIA DE ATENDIMENTO SOCIOEDUCATIVO', 'SUB. ATENDIMENTO SOCIOEDUCATIVO', 'SOCIOEDUCATIVO', 'BELO HORIZONTE');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451376, 'CENTRO INTEGRADO DE ATENDIMENTO AO ADOLESCENTE INFRATOR', 'CIA-BH', 'SOCIOEDUCATIVO', 'BELO HORIZONTE');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451377, 'PRESIDIO DE CATAGUASES/SEDS', 'PRESIDIO DE CATAGUASES', '04ª RISP – Juiz de Fora', 'CATAGUASES');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451380, 'PRESIDIO DE ALMENARA/SEDS', 'PRESIDIO DE ALMENARA', '15ª RISP – Teófilo Otoni', 'ALMENARA');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451382, 'PRESIDIO DE TIMOTEO/SEDS', 'PRESIDIO DE TIMOTEO', '12ª RISP – Ipatinga', 'TIMOTEO');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451384, 'PRESIDIO DE CONCEICAO DAS ALAGOAS/SEDS', 'PRESIDIO DE CONCEICAO DAS ALAGOAS', '05ª RISP – Uberaba', 'CONCEICAO DAS ALAGOAS');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451386, 'PRESIDIO DE CONSELHEIRO PENA/SEDS', 'PRESIDIO DE CONSELHEIRO PENA', '08ª RISP – Governador Valadares', 'CONSELHEIRO PENA');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451388, 'PRESIDIO DE LEOPOLDINA/SEDS', 'PRESIDIO DE LEOPOLDINA', '04ª RISP – Juiz de Fora', 'LEOPOLDINA');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451390, 'PRESIDIO DE JANUARIA/SEDS', 'PRESIDIO DE JANUARIA', '11ª RISP – Montes Claros', 'JANUARIA');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451392, 'PRESIDIO DE MANTENA', 'PRESIDIO DE MANTENA', '08ª RISP – Governador Valadares', 'MANTENA');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451394, 'PRESIDIO DE LAGOA DA PRATA', 'PRESIDIO DE LAGOA DA PRATA', '07ª RISP – Divinópolis', 'LAGOA DA PRATA');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451396, 'PRESIDIO DE ABAETE/SEDS', 'PRESIDIO DE ABAETE/SEDS', '07ª RISP – Divinópolis', 'ABAETE');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451398, 'PRESIDIO DE MANHUACU', 'PRESIDIO DE MANHUACU', '12ª RISP – Ipatinga', 'MANHUACU');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451400, 'PRESIDIO DE JANAUBA', 'PRESIDIO DE JANAUBA', '11ª RISP – Montes Claros', 'JANAUBA');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451402, 'PRESIDIO DE FRUTAL/SEDS', 'PRESIDIO DE FRUTAL', '05ª RISP – Uberaba', 'FRUTAL');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451404, 'PRESIDIO DE ITAUNA/SEDS', 'PRESIDIO DE ITAUNA/SEDS', '07ª RISP – Divinópolis', 'ITAUNA');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451406, 'PRESIDIO DE CAPELINHA', 'PRESIDIO DE CAPELINHA', '14ª RISP – Curvelo', 'CAPELINHA');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451408, 'PRESIDIO DE RIO PIRACICABA/SEDS', 'PRESIDIO DE RIO PIRACICABA/SEDS', '12ª RISP – Ipatinga', 'RIO PIRACICABA');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451417, 'DIRETORIA DO CENTRO INTEGRADO DE COMANDO E CONTROLE', 'DCI/SEJUSP', 'SOCIOEDUCATIVO', 'BELO HORIZONTE');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451420, 'PRESIDIO DE INHAPIM/SEDS', 'PRESIDIO DE INHAPIM/SEDS', '12ª RISP – Ipatinga', 'INHAPIM');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451424, 'PRESIDIO DE SABARA', 'PRESIDIO DE SABARA', '03ª RISP – Vespasiano', 'SABARA');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451426, 'PRESIDIO DE MATOZINHOS', 'PRESIDIO DE MATOZINHOS/SEDS', '19ª RISP - Sete Lagoas', 'MATOZINHOS');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451435, 'PRESIDIO DE JUATUBA', 'PRESIDIO DE JUATUBA', '02ª RISP – Contagem', 'JUATUBA');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451437, 'PRESIDIO DE IBIRITE', 'PRESIDIO DE IBIRITE', '02ª RISP – Contagem', 'IBIRITE');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451439, 'PRESIDIO DE CAETE/SEDS', 'PRESIDIO DE CAETE/SEDS', '03ª RISP – Vespasiano', 'CAETE');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451441, 'PRESIDIO DE NOVA LIMA/SEDS', 'PRESIDIO DE NOVA LIMA', '03ª RISP – Vespasiano', 'NOVA LIMA');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451443, 'PRESIDIO DE LAGOA SANTA', 'PRESIDIO DE LAGOA SANTA', '03ª RISP – Vespasiano', 'LAGOA SANTA');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451445, 'PRESIDIO DE BRUMADINHO', 'PRESIDIO DE BRUMADINHO', '02ª RISP – Contagem', 'BRUMADINHO');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451447, 'PRESIDIO DE SANTA RITA DO SAPUCAI', 'PRESIDIO SANTA RITA DE SAPUCAI', '17ª RISP – Pouso Alegre', 'SANTA RITA DO SAPUCAI');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451465, 'UNIDADE SETORIAL DE PARCERIAS PUBLICO PRIVADA COEGESTAO', 'UNIDADE SETORIAL PPP', '01ª RISP – Belo Horizonte', 'BELO HORIZONTE');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451470, 'UNIDADE CANIL SSP', 'UNIDADE CANIL SSP', '02ª RISP – Contagem', 'RIBEIRAO DAS NEVES');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451471, 'PRESIDIO DE PIRAPORA/SEDS', 'PRESIDIO DE PIRAPORA/SEDS', '14ª RISP – Curvelo', 'PIRAPORA');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451473, 'PRESIDIO DE SACRAMENTO', 'PRESIDIO DE SACRAMENTO', '05ª RISP – Uberaba', 'SACRAMENTO');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451475, 'CARCERAGEM DO FORUM LAFAYETE', 'CARCERAGEM DO FORUM LAFAYETE', '01ª RISP – Belo Horizonte', 'BELO HORIZONTE');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451477, 'CENTRO SOCIOEDUCATIVO HORTO', 'CSEH', 'SOCIOEDUCATIVO', 'BELO HORIZONTE');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451479, 'PRESIDIO DE JABOTICATUBAS', 'PR JABOTICATUBA', '03ª RISP – Vespasiano', 'JABOTICATUBAS');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451481, 'PRESIDIO DE BARAO DE COCAIS', 'PR BARAO DE COCAIS', '12ª RISP – Ipatinga', 'BARAO DE COCAIS');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451483, 'PRESIDIO DE BOA ESPERANCA', 'PRESIDIO DE BOA ESPERANCA', '06ª RISP – Lavras', 'BOA ESPERANCA');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451485, 'PRESIDIO DE BOM SUCESSO', 'PRESIDIO DE BOM SUCESSO', '06ª RISP – Lavras', 'BOM SUCESSO');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451488, 'PRESIDIO DE CARLOS CHAGAS', 'PRESIDIO DE CARLOS CHAGAS', '15ª RISP – Teófilo Otoni', 'CARLOS CHAGAS');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451491, 'PRESIDIO DE MALACACHETA', 'PRESIDIO DE MALACACHETA', '15ª RISP – Teófilo Otoni', 'MALACACHETA');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451494, 'PRESIDIO DE ITACARAMBI', 'PRESIDIO DE ITACARAMBI', '11ª RISP – Montes Claros', 'ITACARAMBI');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451499, 'PRESíDIO DE BAEPENDI', 'PRESIDIO DE BAEPENDI', '17ª RISP – Pouso Alegre', 'BAEPENDI');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451504, 'PRESIDIO DE NANUQUE', 'PRESIDIO DE NANUQUE', '15ª RISP – Teófilo Otoni', 'NANUQUE');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451506, 'PRESIDIO DE MARIANA', 'PRMAR-PRESIDIO DE MARIANA', '03ª RISP – Vespasiano', 'MARIANA');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451508, 'PRESIDIO DE DIAMANTINA', 'PRESIDIO DE DIAMANTINA', '14ª RISP – Curvelo', 'DIAMANTINA');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451510, 'PRESIDIO ABRE CAMPO', 'PRESIDIO ABRE CAMPO', '12ª RISP – Ipatinga', 'ABRE CAMPO');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451512, 'PRESIDIO DE ITAMBACURI', 'PRESIDIO DE ITAMBACURI', '15ª RISP – Teófilo Otoni', 'ITAMBACURI');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451514, 'PRESIDIO DE ARCOS', 'PRARCOS', '07ª RISP – Divinópolis', 'ARCOS');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451516, 'PRESIDIO DE TRES PONTAS', 'PRTP-PRESIDIO DE TRES PONTAS', '06ª RISP – Lavras', 'TRES PONTAS');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451518, 'PRESIDIO DE ITURAMA', 'PRITUR', '05ª RISP – Uberaba', 'ITURAMA');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451520, 'PRESIDIO DE CARANGOLA', 'PRCARA', '04ª RISP – Juiz de Fora', 'CARANGOLA');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451522, 'PRESIDIO DE TUPACIGUARA', 'PRTUPA - PRESIDIO DE TUPACIGUARA', '09ª RISP – Uberlândia', 'TUPACIGUARA');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451524, 'PRESIDIO DE OURO FINO', 'PRESIDIO DE OURO FINO', '17ª RISP – Pouso Alegre', 'OURO FINO');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451526, 'PRESIDIO DE SAO FRANCISCO', 'PRSF', '11ª RISP – Montes Claros', 'SAO FRANCISCO');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451528, 'PRESIDIO DE PRATA', 'PRPRATA', '09ª RISP – Uberlândia', 'PRATA');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451530, 'PRESIDIO PEDRA AZUL', 'PRPED', '15ª RISP – Teófilo Otoni', 'PEDRA AZUL');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451532, 'PRESIDIO DE CAMPOS GERAIS', 'PRESIDIO DE CAMPOS GERAIS', '18ª RISP – Poços de Caldas', 'CAMPOS GERAIS');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451534, 'PRESIDIO DE POMPEU', 'PRESIDIO DE POMPEU', '07ª RISP – Divinópolis', 'POMPEU');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451536, 'PRESIDIO DE MANHUMIRIM', 'PRMAN-PRESIDIO DE MANHUMIRIM', '12ª RISP – Ipatinga', 'MANHUMIRIM');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451539, 'PRESIDIO DE MANGA', 'PRESIDIO DE MANGA', '11ª RISP – Montes Claros', 'MANGA');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451544, 'PRESIDIO DE AGUAS FORMOSAS', 'PRESIDIO DE AGUAS FORMOSAS', '15ª RISP – Teófilo Otoni', 'AGUAS FORMOSAS');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451546, 'PRESIDIO DE SANTOS DUMONT', 'PRESIDIO DE SANTOS DUMONT', '13ª RISP – Barbacena', 'SANTOS DUMONT');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451548, 'PRESIDIO DE JEQUITINHONHA', 'PRESIDIO DE JEQUITINHONHA', '15ª RISP – Teófilo Otoni', 'JEQUITINHONHA');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451550, 'PRESIDIO DE CAMPO BELO', 'PRESIDIO DE CAMPO BELO', '06ª RISP – Lavras', 'CAMPO BELO');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451552, 'PRESIDIO DE PITANGUI', 'PRESIDIO DE PITANGUI', '07ª RISP – Divinópolis', 'PITANGUI');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451556, 'PRESIDIO DE BOM DESPACHO', 'PRESIDIO DE BOM DESPACHO', '07ª RISP – Divinópolis', 'BOM DESPACHO');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451559, 'CENTRO DE INTERNACAO PROVISORIA DE PATOS DE MINAS', 'CEIP PATOS DE MINAS', 'SOCIOEDUCATIVO', 'PATOS DE MINAS');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451561, 'PRESIDIO DE SAO JOAO DA PONTE', 'PRESIDIO DE SAO JOAO DA PONTE', '11ª RISP – Montes Claros', 'SAO JOAO DA PONTE');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451565, 'DIRETORIA DE ATENDIMENTO AO FLAGRANTEADO', 'CEFLAG - CENTRAL DE FLAGRANTES', '01ª RISP – Belo Horizonte', 'BELO HORIZONTE');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451569, 'CENTRAL GERAL DE MONITORAMENTO ELETRONICO', 'CGME', '01ª RISP – Belo Horizonte', 'BELO HORIZONTE');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451571, 'PRESIDIO DE GUANHAES', 'PR DE GUANHAES', '08ª RISP – Governador Valadares', 'GUANHAES');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451573, 'PRESIDIO DE BURITIS', 'PR DE BURITIS', '16ª RISP – Unaí', 'BURITIS');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451578, 'PRESIDIO DE TAIOBEIRAS', 'PRESIDIO DE TAIOBEIRAS', '11ª RISP – Montes Claros', 'TAIOBEIRAS');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451582, 'PRESIDIO DE ANDRELANDIA', 'PRESIDIO DE ANDRELANDIA', '13ª RISP – Barbacena', 'ANDRELANDIA');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451598, 'CENTRO SOCIOEDUCATIVO DE DIVINOPOLIS', 'CSE DIVINOPOLIS', 'SOCIOEDUCATIVO', 'DIVINOPOLIS');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451614, 'CENTRAL DE COMUNICAÇÃO DA SUPERINTENDÊNCIA DE SEGURANÇA PRISIONAL', 'CENTRAL DE COMUNICAÇÃO', '01ª RISP – Belo Horizonte', 'BELO HORIZONTE');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451616, 'ASSESSORIA DE INTELIGENCIA E INFORMACAO', 'ASSESSORIA DE INTELIGENCIA E INFORMACAO', '01ª RISP – Belo Horizonte', 'BELO HORIZONTE');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451617, 'UNIDADE GESTORA DE MONITORIZACAO ELETRONICA', 'UNIDADE GESTORA DE MONITORIZACAO', '01ª RISP – Belo Horizonte', 'BELO HORIZONTE');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451619, 'CENTRO SOCIOEDUCATIVO SANTA CLARA', 'CENTRO SOCIOEDUCATIVO SANTA CLARA', 'SOCIOEDUCATIVO', 'BELO HORIZONTE');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451621, 'PRESIDIO DE ERVALIA', 'PRESIDIO DE ERVALIA', '04ª RISP – Juiz de Fora', 'ERVALIA');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451625, 'CENTRAL DE ESCOLTAS ESPECIAIS DE JUIZ DE FORA', 'CENTRAL DE ESCOLTAS ESPECIAIS', '04ª RISP – Juiz de Fora', 'JUIZ DE FORA');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451628, 'PRESIDIO DE EXTREMA', 'PRESIDIO DE EXTREMA', '17ª RISP – Pouso Alegre', 'EXTREMA');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451633, 'CENTRAL INTEGRADA DE ESCOLTAS DE RIBEIRAO DAS NEVES', 'CENTRAL DE ESCOLTAS DE RIBEIRA DAS NEVES', '02ª RISP – Contagem', 'RIBEIRAO DAS NEVES');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451636, 'PRESIDIO DE NOVO CRUZEIRO', 'PRESIDIO DE NOVO CRUZEIRO', '15ª RISP – Teófilo Otoni', 'NOVO CRUZEIRO');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451638, 'CENTRO SOCIOEDUCATIVO DE DIVINOPOLIS A DESATIVAR', 'CENTRO SOCIOEDUCATIVO DE DIVINOPOLIS', 'SOCIOEDUCATIVO', 'DIVINOPOLIS');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451644, 'CENTRO SOCIOEDUCATIVO DE JUIZ DE FORA', 'CSE JUIZ DE FORA', 'SOCIOEDUCATIVO', 'JUIZ DE FORA');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451651, 'CENTRO SOCIOEDUCATIVO DE IPATINGA', 'CENTRO SOCIOEDUCATIVO DE IPATINGA', 'SOCIOEDUCATIVO', 'IPATINGA');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451653, 'PRESIDIO DE CONGONHAS', 'PRESIDIO DE CONGONHAS', '13ª RISP – Barbacena', 'CONGONHAS');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451655, 'COMPLEXO PENAL PARCERIA PUBLICO PRIVADA', 'COMPLEXO PPP', '02ª RISP – Contagem', 'RIBEIRAO DAS NEVES');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451669, 'PRESIDIO DE JACINTO', 'PRESIDIO DE JACINTO', '15ª RISP – Teófilo Otoni', 'JACINTO');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451671, 'CENTRO SOCIOEDUCATIVO DE RIBEIRAO DAS NEVES', 'CSE DE RIBEIRAO DAS NEVES', 'SOCIOEDUCATIVO', 'RIBEIRAO DAS NEVES');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451672, 'PRESIDIO DE ACUCENA', 'PRESIDIO DE ACUCENA', '12ª RISP – Ipatinga', 'ACUCENA');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451674, 'PRESIDIO DE BICAS', 'PRESIDIO DE BICAS', '04ª RISP – Juiz de Fora', 'BICAS');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451676, 'PRESIDIO DE EUGENOPOLIS', 'PRESIDIO DE EUGENOPOLIS', '04ª RISP – Juiz de Fora', 'EUGENOPOLIS');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451678, 'PRESIDIO DE BOCAIUVA', 'PRESIDIO DE BOCAIUVA', '11ª RISP – Montes Claros', 'BOCAIUVA');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451839, 'PRESIDIO DE RIO POMBA', 'PRESIDIO DE RIO POMBA', '04ª RISP – Juiz de Fora', 'RIO POMBA');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451840, 'PRESIDIO DE BOTELHOS', 'PRESIDIO DE BOTELHOS', '18ª RISP – Poços de Caldas', 'BOTELHOS');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451841, 'PRESIDIO DE PECANHA', 'PRESIDIO DE PECANHA', '08ª RISP – Governador Valadares', 'PECANHA');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451842, 'PRESIDIO DE LUZ', 'PRESIDIO DE LUZ', '07ª RISP – Divinópolis', 'LUZ');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451843, 'PRESIDIO DE RESENDE COSTA', 'PRESIDIO DE RESENDE COSTA', '13ª RISP – Barbacena', 'RESENDE COSTA');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451844, 'PRESIDIO DE MATIAS BARBOSA', 'PRESIDIO DE MATIAS BARBOSA', '04ª RISP – Juiz de Fora', 'MATIAS BARBOSA');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451846, 'PRESIDIO DE SAO JOAO EVANGELISTA', 'PRESIDIO DE SAO JOAO EVANGELISTA', '08ª RISP – Governador Valadares', 'SAO JOAO EVANGELISTA');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451847, 'PRESIDIO DE TURMALINA', 'PRESIDIO DE TURMALINA', '14ª RISP – Curvelo', 'TURMALINA');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451848, 'PRESIDIO DE PERDIZES', 'PRESIDIO DE PERDIZES', '05ª RISP – Uberaba', 'PERDIZES');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451849, 'PRESIDIO VARZEA DA PALMA', 'PRESIDIO VARZEA DA PALMA', '14ª RISP – Curvelo', 'VARZEA DA PALMA');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451850, 'PRESIDIO DE TRES MARIAS', 'PRESIDIO DE TRES MARIAS', '14ª RISP – Curvelo', 'TRES MARIAS');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451851, 'PRESIDIO DE CORINTO', 'PRESIDIO DE CORINTO', '14ª RISP – Curvelo', 'CORINTO');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451853, 'PRESIDIO DE ITAMARANDIBA', 'PRESIDIO DE ITAMARANDIBA', '14ª RISP – Curvelo', 'ITAMARANDIBA');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451861, 'PRESIDIO DE MONTE AZUL', 'PRESIDIO DE MONTE AZUL', '11ª RISP – Montes Claros', 'MONTE AZUL');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451871, 'PRESIDIO DE MONTE SANTO DE MINAS', 'PRESIDIO DE MONTE SANTO DE MINAS', '18ª RISP – Poços de Caldas', 'MONTE SANTO DE MINAS');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451873, 'PRESIDIO DE MACHADO', 'PRESIDIO DE MACHADO', '18ª RISP – Poços de Caldas', 'MACHADO');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451876, 'PRESIDIO DE SANTA VITORIA', 'PRESIDIO DE SANTA VITORIA', '09ª RISP – Uberlândia', 'SANTA VITORIA');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451880, 'PRESIDIO DE CANAPOLIS', 'PRESIDIO DE CANAPOLIS', '09ª RISP – Uberlândia', 'CANAPOLIS');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451882, 'PRESIDIO DE CANDEIAS', 'PRESIDIO DE CANDEIAS', '06ª RISP – Lavras', 'CANDEIAS');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451884, 'PRESIDIO DE AIMORES', 'PRESIDIO DE AIMORES', '08ª RISP – Governador Valadares', 'AIMORES');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451886, 'PRESIDIO DE TARUMIRIM', 'PRESIDIO DE TARUMIRIM', '08ª RISP – Governador Valadares', 'TARUMIRIM');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451888, 'PRESIDIO DE SALINAS', 'PRESIDIO DE SALINAS', '11ª RISP – Montes Claros', 'SALINAS');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451892, 'PRESIDIO DE BAMBUI', 'PRESIDIO DE BAMBUI', '07ª RISP – Divinópolis', 'BAMBUI');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451894, 'PRESIDIO DE PORTEIRINHA', 'PRESIDIO DE PORTEIRINHA', '11ª RISP – Montes Claros', 'PORTEIRINHA');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451898, 'PRESIDIO DE ITAPAGIPE', 'PRESIDIO DE ITAPAGIPE', '05ª RISP – Uberaba', 'ITAPAGIPE');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451906, 'PRESIDIO DE NEPOMUCENO', 'PRESIDIO DE NEPOMUCENO', '06ª RISP – Lavras', 'NEPOMUCENO');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451913, '2° DIRETORIA REGIONAL DE ADMINISTRACAO PRISIONAL', '2° DRAP', '02ª RISP – Contagem', 'RIBEIRAO DAS NEVES');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451915, '3A DIRETORIA REGIONAL DE ADMINISTRACAO PRISIONAL', '3A DRAP', '03ª RISP – Vespasiano', 'LAGOA SANTA');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451927, '10° DIRETORIA REGIONAL DE ADMINISTRACAO PRISIONAL', '10°DRAP', '10ª RISP – Patos de Minas', 'CARMO DO PARANAIBA');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451935, '15° DIRETORIA REGIONAL DE ADMINISTRACAO PRISIONAL', '15°DRAP', '15ª RISP – Teófilo Otoni', 'TEOFILO OTONI');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451923, '8° DIRETORIA REGIONAL DE ADMINISTRACAO PRISIONAL', '8°DRAP', '8ª RISP – Governador Valadares', 'GOVERNADOR VALADARES');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451179, 'CENTRO DE INTERNACAO PROVISORIA DE SETE LAGOAS', 'CEIP SETE LAGOAS', '19ª RISP - Sete Lagoas', 'SETE LAGOAS');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451379, 'DIRETORIA DE SEGURANCA SOCIOEDUCATIVA', 'DIRETORIA DE SEGURANCA SOCIOEDUCATIVA', '1ª RISP – Belo Horizonte', 'BELO HORIZONTE');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451002, 'DIRETORIA DE TRANSPORTES E SERVICOS GERAIS', 'DIRETORIA DE TRANSPORTES E SERVICOS', '1ª RISP – Belo Horizonte', 'BELO HORIZONTE');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451540, 'PRESIDIO DE ITABIRITO', 'PRESIDIO DE ITABIRITO', '3ª RISP – Vespasiano', 'ITABIRITO');
insert into unity(unity_code, unity, bo_abreviation, risp, city) values (1451173, 'SSP - DIRETORIA DE SEGURANCA INTERNA', 'DSI', '1ª RISP – Belo Horizonte', 'BELO HORIZONTE');