insert into risp (risp, city,city_fix) values('1ª RISP – Belo Horizonte', 'Belo Horizonte', 'BELO HORIZONTE');
insert into risp (risp, city,city_fix) values('2ª RISP – Contagem', 'Betim', 'BETIM');
insert into risp (risp, city,city_fix) values('2ª RISP – Contagem', 'Bonfim', 'BONFIM');
insert into risp (risp, city,city_fix) values('2ª RISP – Contagem', 'Brumadinho', 'BRUMADINHO');
insert into risp (risp, city,city_fix) values('2ª RISP – Contagem', 'Contagem', 'CONTAGEM');
insert into risp (risp, city,city_fix) values('2ª RISP – Contagem', 'Crucilândia', 'CRUCILANDIA');
insert into risp (risp, city,city_fix) values('2ª RISP – Contagem', 'Esmeraldas', 'ESMERALDAS');
insert into risp (risp, city,city_fix) values('2ª RISP – Contagem', 'Ibirite', 'IBIRITE');
insert into risp (risp, city,city_fix) values('2ª RISP – Contagem', 'Igarapé', 'IGARAPE');
insert into risp (risp, city,city_fix) values('2ª RISP – Contagem', 'Itaguara', 'ITAGUARA');
insert into risp (risp, city,city_fix) values('2ª RISP – Contagem', 'Juatuba', 'JUATUBA');
insert into risp (risp, city,city_fix) values('2ª RISP – Contagem', 'Mario Campos', 'MARIO CAMPOS');
insert into risp (risp, city,city_fix) values('2ª RISP – Contagem', 'Mateus Leme', 'MATEUS LEME');
insert into risp (risp, city,city_fix) values('2ª RISP – Contagem', 'Piedade dos Gerais', 'PIEDADE DOS GERAIS');
insert into risp (risp, city,city_fix) values('2ª RISP – Contagem', 'Ribeirão das Neves', 'RIBEIRAO DAS NEVES');
insert into risp (risp, city,city_fix) values('2ª RISP – Contagem', 'Rio Manso', 'RIO MANSO');
insert into risp (risp, city,city_fix) values('2ª RISP – Contagem', 'São Joaquim de Bicas', 'SAO JOAQUIM DE BICAS');
insert into risp (risp, city,city_fix) values('2ª RISP – Contagem', 'Sarzedo', 'SARZEDO');
insert into risp (risp, city,city_fix) values('3ª RISP – Vespasiano', 'Caete', 'CAETE');
insert into risp (risp, city,city_fix) values('3ª RISP – Vespasiano', 'Confins', 'CONFINS');
insert into risp (risp, city,city_fix) values('3ª RISP – Vespasiano', 'Diogo de Vasconcelos', 'DIOGO DE VASCONCELOS');
insert into risp (risp, city,city_fix) values('3ª RISP – Vespasiano', 'Itabirito', 'ITABIRITO');
insert into risp (risp, city,city_fix) values('3ª RISP – Vespasiano', 'Jaboticatubas', 'JABOTICATUBAS');
insert into risp (risp, city,city_fix) values('3ª RISP – Vespasiano', 'Lagoa Santa', 'LAGOA SANTA');
insert into risp (risp, city,city_fix) values('3ª RISP – Vespasiano', 'Mariana', 'MARIANA');
insert into risp (risp, city,city_fix) values('3ª RISP – Vespasiano', 'Nova Lima', 'NOVA LIMA');
insert into risp (risp, city,city_fix) values('3ª RISP – Vespasiano', 'Nova União', 'NOVA UNIAO');
insert into risp (risp, city,city_fix) values('3ª RISP – Vespasiano', 'Ouro Preto', 'OURO PRETO');
insert into risp (risp, city,city_fix) values('3ª RISP – Vespasiano', 'Raposos', 'RAPOSOS');
insert into risp (risp, city,city_fix) values('3ª RISP – Vespasiano', 'Rio Acima', 'RIO ACIMA');
insert into risp (risp, city,city_fix) values('3ª RISP – Vespasiano', 'Sabará', 'SABARA');
insert into risp (risp, city,city_fix) values('3ª RISP – Vespasiano', 'Santa Luzia', 'SANTA LUZIA');
insert into risp (risp, city,city_fix) values('3ª RISP – Vespasiano', 'Santana do Riacho', 'SANTANA DO RIACHO');
insert into risp (risp, city,city_fix) values('3ª RISP – Vespasiano', 'São José da Lapa', 'SAO JOSE DA LAPA');
insert into risp (risp, city,city_fix) values('3ª RISP – Vespasiano', 'Taquaracu de Minas', 'TAQUARACU DE MINAS');
insert into risp (risp, city,city_fix) values('3ª RISP – Vespasiano', 'Vespasiano', 'VESPASIANO');
insert into risp (risp, city,city_fix) values('4ª RISP – Juiz de Fora', 'Além Paraíba', 'ALEM PARAIBA');
insert into risp (risp, city,city_fix) values('4ª RISP – Juiz de Fora', 'Antônio Prado de Minas', 'ANTÔNIO PRADO DE MINAS');
insert into risp (risp, city,city_fix) values('4ª RISP – Juiz de Fora', 'Araponga', 'ARAPONGA');
insert into risp (risp, city,city_fix) values('4ª RISP – Juiz de Fora', 'Argirita', 'ARGIRITA');
insert into risp (risp, city,city_fix) values('4ª RISP – Juiz de Fora', 'Astolfo Dutra', 'ASTOLFO DUTRA');
insert into risp (risp, city,city_fix) values('4ª RISP – Juiz de Fora', 'Barão de Monte Alto', 'BARAO DE MONTE ALTO');
insert into risp (risp, city,city_fix) values('4ª RISP – Juiz de Fora', 'Belmiro Braga', 'BELMIRO BRAGA');
insert into risp (risp, city,city_fix) values('4ª RISP – Juiz de Fora', 'Bicas', 'BICAS');
insert into risp (risp, city,city_fix) values('4ª RISP – Juiz de Fora', 'Brás Pires', 'BRAS PIRES');
insert into risp (risp, city,city_fix) values('4ª RISP – Juiz de Fora', 'Cajuri', 'CAJURI');
insert into risp (risp, city,city_fix) values('4ª RISP – Juiz de Fora', 'Canaã', 'CANAA');
insert into risp (risp, city,city_fix) values('4ª RISP – Juiz de Fora', 'Carangola', 'CARANGOLA');
insert into risp (risp, city,city_fix) values('4ª RISP – Juiz de Fora', 'Cataguases', 'CATAGUASES');
insert into risp (risp, city,city_fix) values('4ª RISP – Juiz de Fora', 'Chácara', 'CHACARA');
insert into risp (risp, city,city_fix) values('4ª RISP – Juiz de Fora', 'Chiador', 'CHIADOR');
insert into risp (risp, city,city_fix) values('4ª RISP – Juiz de Fora', 'Coimbra', 'COIMBRA');
insert into risp (risp, city,city_fix) values('4ª RISP – Juiz de Fora', 'Coronel Pacheco', 'CORONEL PACHECO');
insert into risp (risp, city,city_fix) values('4ª RISP – Juiz de Fora', 'Descoberto', 'DESCOBERTO');
insert into risp (risp, city,city_fix) values('4ª RISP – Juiz de Fora', 'Divinésia', 'DIVINESIA');
insert into risp (risp, city,city_fix) values('4ª RISP – Juiz de Fora', 'Divino', 'DIVINO');
insert into risp (risp, city,city_fix) values('4ª RISP – Juiz de Fora', 'Dona Eusébia', 'DONA EUSEBIA');
insert into risp (risp, city,city_fix) values('4ª RISP – Juiz de Fora', 'Dores do Turvo', 'DORES DO TURVO');
insert into risp (risp, city,city_fix) values('4ª RISP – Juiz de Fora', 'Ervália', 'ERVALIA');
insert into risp (risp, city,city_fix) values('4ª RISP – Juiz de Fora', 'Estrela Dalva', 'ESTRELA DALVA');
insert into risp (risp, city,city_fix) values('4ª RISP – Juiz de Fora', 'Eugenópolis', 'EUGENOPOLIS');
insert into risp (risp, city,city_fix) values('4ª RISP – Juiz de Fora', 'Faria Lemos', 'FARIA LEMOS');
insert into risp (risp, city,city_fix) values('4ª RISP – Juiz de Fora', 'Fervedouro', 'FERVEDOURO');
insert into risp (risp, city,city_fix) values('4ª RISP – Juiz de Fora', 'Goiânia', 'GOIANIA');
insert into risp (risp, city,city_fix) values('4ª RISP – Juiz de Fora', 'Guarani', 'GUARANI');
insert into risp (risp, city,city_fix) values('4ª RISP – Juiz de Fora', 'Guaraná', 'GUARANA');
insert into risp (risp, city,city_fix) values('4ª RISP – Juiz de Fora', 'Guidoval', 'GUIDOVAL');
insert into risp (risp, city,city_fix) values('4ª RISP – Juiz de Fora', 'Guiricema', 'GUIRICEMA');
insert into risp (risp, city,city_fix) values('4ª RISP – Juiz de Fora', 'Itamarati de Minas', 'ITAMARATI DE MINAS');
insert into risp (risp, city,city_fix) values('4ª RISP – Juiz de Fora', 'Juiz de Fora', 'JUIZ DE FORA');
insert into risp (risp, city,city_fix) values('4ª RISP – Juiz de Fora', 'Laranjal', 'LARANJAL');
insert into risp (risp, city,city_fix) values('4ª RISP – Juiz de Fora', 'Leopoldina', 'LEOPOLDINA');
insert into risp (risp, city,city_fix) values('4ª RISP – Juiz de Fora', 'Lima Duarte', 'LIMA DUARTE');
insert into risp (risp, city,city_fix) values('4ª RISP – Juiz de Fora', 'Mar de Espanha', 'MAR DE ESPANHA');
insert into risp (risp, city,city_fix) values('4ª RISP – Juiz de Fora', 'Maripa de Minas', 'MARIPA DE MINAS');
insert into risp (risp, city,city_fix) values('4ª RISP – Juiz de Fora', 'Matias Barbosa', 'MATIAS BARBOSA');
insert into risp (risp, city,city_fix) values('4ª RISP – Juiz de Fora', 'Mercês', 'MERCES');
insert into risp (risp, city,city_fix) values('4ª RISP – Juiz de Fora', 'Miradouro', 'MIRADOURO');
insert into risp (risp, city,city_fix) values('4ª RISP – Juiz de Fora', 'Miraí', 'MIRAI');
insert into risp (risp, city,city_fix) values('4ª RISP – Juiz de Fora', 'Muriaé', 'MURIAE');
insert into risp (risp, city,city_fix) values('4ª RISP – Juiz de Fora', 'Olária', 'OLARIA');
insert into risp (risp, city,city_fix) values('4ª RISP – Juiz de Fora', 'Orizânia', 'ORIZANIA');
insert into risp (risp, city,city_fix) values('4ª RISP – Juiz de Fora', 'Palma', 'PALMA');
insert into risp (risp, city,city_fix) values('4ª RISP – Juiz de Fora', 'Patrocínio do Muriaé', 'PATROCINIO DO MURIAE');
insert into risp (risp, city,city_fix) values('4ª RISP – Juiz de Fora', 'Paula Cândido', 'PAULA CANDIDO');
insert into risp (risp, city,city_fix) values('4ª RISP – Juiz de Fora', 'Pedra do Anta', 'PEDRA DO ANTA');
insert into risp (risp, city,city_fix) values('4ª RISP – Juiz de Fora', 'Pedra Dourada', 'PEDRA DOURADA');
insert into risp (risp, city,city_fix) values('4ª RISP – Juiz de Fora', 'Pedro Teixeira', 'PEDRO TEIXEIRA');
insert into risp (risp, city,city_fix) values('4ª RISP – Juiz de Fora', 'Pequeri', 'PEQUERI');
insert into risp (risp, city,city_fix) values('4ª RISP – Juiz de Fora', 'Piaú', 'PIAU');
insert into risp (risp, city,city_fix) values('4ª RISP – Juiz de Fora', 'Pirapetinga', 'PIRAPETINGA');
insert into risp (risp, city,city_fix) values('4ª RISP – Juiz de Fora', 'Pirauba', 'PIRAUBA');
insert into risp (risp, city,city_fix) values('4ª RISP – Juiz de Fora', 'Recreio', 'RECREIO');
insert into risp (risp, city,city_fix) values('4ª RISP – Juiz de Fora', 'Rio Novo', 'RIO NOVO');
insert into risp (risp, city,city_fix) values('4ª RISP – Juiz de Fora', 'Rio Pomba', 'RIO POMBA');
insert into risp (risp, city,city_fix) values('4ª RISP – Juiz de Fora', 'Rio Preto', 'RIO PRETO');
insert into risp (risp, city,city_fix) values('4ª RISP – Juiz de Fora', 'Rochedo de Minas', 'ROCHEDO DE MINAS');
insert into risp (risp, city,city_fix) values('4ª RISP – Juiz de Fora', 'Rodeiro', 'RODEIRO');
insert into risp (risp, city,city_fix) values('4ª RISP – Juiz de Fora', 'Rosário da Limeira', 'ROSARIO DA LIMEIRA');
insert into risp (risp, city,city_fix) values('4ª RISP – Juiz de Fora', 'Santa Bárbara do Monte Verde', 'SANTA BARBARA DO MONTE VERDE');
insert into risp (risp, city,city_fix) values('4ª RISP – Juiz de Fora', 'Santa Rita do Jacutinga', 'SANTA RITA DO JACUTINGA');
insert into risp (risp, city,city_fix) values('4ª RISP – Juiz de Fora', 'Santana de Cataguases', 'SANTANA DE CATAGUASES');
insert into risp (risp, city,city_fix) values('4ª RISP – Juiz de Fora', 'Santana do Deserto', 'SANTANA DO DESERTO');
insert into risp (risp, city,city_fix) values('4ª RISP – Juiz de Fora', 'Santo Antônio do Aventureiro', 'SANTO ANTÔNIO DO AVENTUREIRO');
insert into risp (risp, city,city_fix) values('4ª RISP – Juiz de Fora', 'São Francisco do Glória', 'SAO FRANCISCO DO GLORIA');
insert into risp (risp, city,city_fix) values('4ª RISP – Juiz de Fora', 'São Geraldo', 'SAO GERALDO');
insert into risp (risp, city,city_fix) values('4ª RISP – Juiz de Fora', 'São João Nepomuceno', 'SAO JOAO NEPOMUCENO');
insert into risp (risp, city,city_fix) values('4ª RISP – Juiz de Fora', 'São Miguel do Anta', 'SAO MIGUEL DO ANTA');
insert into risp (risp, city,city_fix) values('4ª RISP – Juiz de Fora', 'São Sebastião da Vargem Alegre', 'SAO SEBASTIAO DA VARGEM ALEGRE');
insert into risp (risp, city,city_fix) values('4ª RISP – Juiz de Fora', 'Senador Cortês', 'SENADOR CORTES');
insert into risp (risp, city,city_fix) values('4ª RISP – Juiz de Fora', 'Senador Firmino', 'SENADOR FIRMINO');
insert into risp (risp, city,city_fix) values('4ª RISP – Juiz de Fora', 'Silveirania', 'SILVEIRANIA');
insert into risp (risp, city,city_fix) values('4ª RISP – Juiz de Fora', 'Simão Pereira', 'SIMAO PEREIRA');
insert into risp (risp, city,city_fix) values('4ª RISP – Juiz de Fora', 'Tabuleiro', 'TABULEIRO');
insert into risp (risp, city,city_fix) values('4ª RISP – Juiz de Fora', 'Teixeiras', 'TEIXEIRAS');
insert into risp (risp, city,city_fix) values('4ª RISP – Juiz de Fora', 'Tocantins', 'TOCANTINS');
insert into risp (risp, city,city_fix) values('4ª RISP – Juiz de Fora', 'Tombos', 'TOMBOS');
insert into risp (risp, city,city_fix) values('4ª RISP – Juiz de Fora', 'Uba', 'UBA');
insert into risp (risp, city,city_fix) values('4ª RISP – Juiz de Fora', 'Viçosa', 'VICOSA');
insert into risp (risp, city,city_fix) values('4ª RISP – Juiz de Fora', 'Vieiras', 'VIEIRAS');
insert into risp (risp, city,city_fix) values('4ª RISP – Juiz de Fora', 'Visconde do Rio Branco', 'VISCONDE DO RIO BRANCO');
insert into risp (risp, city,city_fix) values('4ª RISP – Juiz de Fora', 'Volta Grande', 'VOLTA GRANDE');
insert into risp (risp, city,city_fix) values('5ª RISP – Uberaba', 'Água Comprida', 'AGUA COMPRIDA');
insert into risp (risp, city,city_fix) values('5ª RISP – Uberaba', 'Araxá', 'ARAXA');
insert into risp (risp, city,city_fix) values('5ª RISP – Uberaba', 'Campina Verde', 'CAMPINA VERDE');
insert into risp (risp, city,city_fix) values('5ª RISP – Uberaba', 'Campos Altos', 'CAMPOS ALTOS');
insert into risp (risp, city,city_fix) values('5ª RISP – Uberaba', 'Carneirinho', 'CARNEIRINHO');
insert into risp (risp, city,city_fix) values('5ª RISP – Uberaba', 'Comendador Gomes', 'COMENDADOR GOMES');
insert into risp (risp, city,city_fix) values('5ª RISP – Uberaba', 'Conceição das Alagoas', 'CONCEICAO DAS ALAGOAS');
insert into risp (risp, city,city_fix) values('5ª RISP – Uberaba', 'Conquista', 'CONQUISTA');
insert into risp (risp, city,city_fix) values('5ª RISP – Uberaba', 'Delta', 'DELTA');
insert into risp (risp, city,city_fix) values('5ª RISP – Uberaba', 'Fronteira', 'FRONTEIRA');
insert into risp (risp, city,city_fix) values('5ª RISP – Uberaba', 'Frutal', 'FRUTAL');
insert into risp (risp, city,city_fix) values('5ª RISP – Uberaba', 'Ibiá', 'IBIA');
insert into risp (risp, city,city_fix) values('5ª RISP – Uberaba', 'Itapagipe', 'ITAPAGIPE');
insert into risp (risp, city,city_fix) values('5ª RISP – Uberaba', 'Iturama', 'ITURAMA');
insert into risp (risp, city,city_fix) values('5ª RISP – Uberaba', 'Limeira do Oeste', 'LIMEIRA DO OESTE');
insert into risp (risp, city,city_fix) values('5ª RISP – Uberaba', 'Nova Ponte', 'NOVA PONTE');
insert into risp (risp, city,city_fix) values('5ª RISP – Uberaba', 'Pedrinópolis', 'PEDRINOPOLIS');
insert into risp (risp, city,city_fix) values('5ª RISP – Uberaba', 'Perdizes', 'PERDIZES');
insert into risp (risp, city,city_fix) values('5ª RISP – Uberaba', 'Pirajuba', 'PIRAJUBA');
insert into risp (risp, city,city_fix) values('5ª RISP – Uberaba', 'Planura', 'PLANURA');
insert into risp (risp, city,city_fix) values('5ª RISP – Uberaba', 'Pratinha', 'PRATINHA');
insert into risp (risp, city,city_fix) values('5ª RISP – Uberaba', 'Sacramento', 'SACRAMENTO');
insert into risp (risp, city,city_fix) values('5ª RISP – Uberaba', 'Santa Juliana', 'SANTA JULIANA');
insert into risp (risp, city,city_fix) values('5ª RISP – Uberaba', 'Santa Rosa de Sales', 'SANTA ROSA DE SALES');
insert into risp (risp, city,city_fix) values('5ª RISP – Uberaba', 'Tapira', 'TAPIRA');
insert into risp (risp, city,city_fix) values('5ª RISP – Uberaba', 'Uberaba', 'UBERABA');
insert into risp (risp, city,city_fix) values('5ª RISP – Uberaba', 'União de Minas', 'UNIAO DE MINAS');
insert into risp (risp, city,city_fix) values('5ª RISP – Uberaba', 'Veríssimo', 'VERISSIMO');
insert into risp (risp, city,city_fix) values('6ª RISP – Lavras', 'Aguanil', 'AGUANIL');
insert into risp (risp, city,city_fix) values('6ª RISP – Lavras', 'Boa Esperança', 'BOA ESPERANCA');
insert into risp (risp, city,city_fix) values('6ª RISP – Lavras', 'Bom Sucesso', 'BOM SUCESSO');
insert into risp (risp, city,city_fix) values('6ª RISP – Lavras', 'Cambuquira', 'CAMBUQUIRA');
insert into risp (risp, city,city_fix) values('6ª RISP – Lavras', 'Campanha', 'CAMPANHA');
insert into risp (risp, city,city_fix) values('6ª RISP – Lavras', 'Campo Belo', 'CAMPO BELO');
insert into risp (risp, city,city_fix) values('6ª RISP – Lavras', 'Cana Verde', 'CANA VERDE');
insert into risp (risp, city,city_fix) values('6ª RISP – Lavras', 'Candeias', 'CANDEIAS');
insert into risp (risp, city,city_fix) values('6ª RISP – Lavras', 'Carmos da Cachoeira', 'CARMOS DA CACHOEIRA');
insert into risp (risp, city,city_fix) values('6ª RISP – Lavras', 'Carmo da Mata', 'CARMO DA MATA');
insert into risp (risp, city,city_fix) values('6ª RISP – Lavras', 'Camopólis de Minas', 'CAMOPOLIS DE MINAS');
insert into risp (risp, city,city_fix) values('6ª RISP – Lavras', 'Carrancas', 'CARRANCAS');
insert into risp (risp, city,city_fix) values('6ª RISP – Lavras', 'Conceição do Rio Verde', 'CONCEICAO DO RIO VERDE');
insert into risp (risp, city,city_fix) values('6ª RISP – Lavras', 'Coqueiral', 'COQUEIRAL');
insert into risp (risp, city,city_fix) values('6ª RISP – Lavras', 'Cristais', 'CRISTAIS');
insert into risp (risp, city,city_fix) values('6ª RISP – Lavras', 'Elói Mendes', 'ELOI MENDES');
insert into risp (risp, city,city_fix) values('6ª RISP – Lavras', 'Guapé', 'GUAPE');
insert into risp (risp, city,city_fix) values('6ª RISP – Lavras', 'Ibituruna', 'IBITURUNA');
insert into risp (risp, city,city_fix) values('6ª RISP – Lavras', 'Ijaci', 'IJACI');
insert into risp (risp, city,city_fix) values('6ª RISP – Lavras', 'Ilicínea', 'ILICINEA');
insert into risp (risp, city,city_fix) values('6ª RISP – Lavras', 'Ingaí', 'INGAI');
insert into risp (risp, city,city_fix) values('6ª RISP – Lavras', 'Itumirim', 'ITUMIRIM');
insert into risp (risp, city,city_fix) values('6ª RISP – Lavras', 'Itutinga', 'ITUTINGA');
insert into risp (risp, city,city_fix) values('6ª RISP – Lavras', 'Jesuânia', 'JESUANIA');
insert into risp (risp, city,city_fix) values('6ª RISP – Lavras', 'Lambari', 'LAMBARI');
insert into risp (risp, city,city_fix) values('6ª RISP – Lavras', 'Lavras', 'LAVRAS');
insert into risp (risp, city,city_fix) values('6ª RISP – Lavras', 'Luminárias', 'LUMINARIAS');
insert into risp (risp, city,city_fix) values('6ª RISP – Lavras', 'Monsenhor Paulo', 'MONSENHOR PAULO');
insert into risp (risp, city,city_fix) values('6ª RISP – Lavras', 'Nepomuceno', 'NEPOMUCENO');
insert into risp (risp, city,city_fix) values('6ª RISP – Lavras', 'Olímpio Noronha', 'OLIMPIO NORONHA');
insert into risp (risp, city,city_fix) values('6ª RISP – Lavras', 'Oliveira', 'OLIVEIRA');
insert into risp (risp, city,city_fix) values('6ª RISP – Lavras', 'Passa Tempo', 'PASSA TEMPO');
insert into risp (risp, city,city_fix) values('6ª RISP – Lavras', 'Perdões', 'PERDOES');
insert into risp (risp, city,city_fix) values('6ª RISP – Lavras', 'Piracema', 'PIRACEMA');
insert into risp (risp, city,city_fix) values('6ª RISP – Lavras', 'Ribeirão Vermelho', 'RIBEIRAO VERMELHO');
insert into risp (risp, city,city_fix) values('6ª RISP – Lavras', 'Santana da Vargem', 'SANTANA DA VARGEM');
insert into risp (risp, city,city_fix) values('6ª RISP – Lavras', 'Santana do Jacaré', 'SANTANA DO JACARE');
insert into risp (risp, city,city_fix) values('6ª RISP – Lavras', 'Santo Antônio do Amparo', 'SANTO ANTÔNIO DO AMPARO');
insert into risp (risp, city,city_fix) values('6ª RISP – Lavras', 'São Bento Abade', 'SAO BENTO ABADE');
insert into risp (risp, city,city_fix) values('6ª RISP – Lavras', 'São Francisco de Paula', 'SAO FRANCISCO DE PAULA');
insert into risp (risp, city,city_fix) values('6ª RISP – Lavras', 'São Tomé das Letras', 'SAO TOME DAS LETRAS');
insert into risp (risp, city,city_fix) values('6ª RISP – Lavras', 'Três Corações', 'TRES CORACOES');
insert into risp (risp, city,city_fix) values('6ª RISP – Lavras', 'Três Pontas', 'TRES PONTAS');
insert into risp (risp, city,city_fix) values('6ª RISP – Lavras', 'Varginha', 'VARGINHA');
insert into risp (risp, city,city_fix) values('7ª RISP – Divinópolis', 'Abaete', 'ABAETE');
insert into risp (risp, city,city_fix) values('7ª RISP – Divinópolis', 'Araújos', 'ARAUJOS');
insert into risp (risp, city,city_fix) values('7ª RISP – Divinópolis', 'Arcos', 'ARCOS');
insert into risp (risp, city,city_fix) values('7ª RISP – Divinópolis', 'Bambuí', 'BAMBUI');
insert into risp (risp, city,city_fix) values('7ª RISP – Divinópolis', 'Biquinhas', 'BIQUINHAS');
insert into risp (risp, city,city_fix) values('7ª RISP – Divinópolis', 'Bom Despacho', 'BOM DESPACHO');
insert into risp (risp, city,city_fix) values('7ª RISP – Divinópolis', 'Camacho', 'CAMACHO');
insert into risp (risp, city,city_fix) values('7ª RISP – Divinópolis', 'Carmo do Cajuru', 'CARMO DO CAJURU');
insert into risp (risp, city,city_fix) values('7ª RISP – Divinópolis', 'Cedro do Abaete', 'CEDRO DO ABAETE');
insert into risp (risp, city,city_fix) values('7ª RISP – Divinópolis', 'Claudio', 'CLAUDIO');
insert into risp (risp, city,city_fix) values('7ª RISP – Divinópolis', 'Conceição do Pará', 'CONCEICAO DO PARA');
insert into risp (risp, city,city_fix) values('7ª RISP – Divinópolis', 'Córrego Danta', 'CORREGO DANTA');
insert into risp (risp, city,city_fix) values('7ª RISP – Divinópolis', 'Córrego Fundo', 'CORREGO FUNDO');
insert into risp (risp, city,city_fix) values('7ª RISP – Divinópolis', 'Divinópolis', 'DIVINOPOLIS');
insert into risp (risp, city,city_fix) values('7ª RISP – Divinópolis', 'Dores do Indaiá', 'DORES DO INDAIA');
insert into risp (risp, city,city_fix) values('7ª RISP – Divinópolis', 'Estrela do Indaiá', 'ESTRELA DO INDAIA');
insert into risp (risp, city,city_fix) values('7ª RISP – Divinópolis', 'Florestal', 'FLORESTAL');
insert into risp (risp, city,city_fix) values('7ª RISP – Divinópolis', 'Formiga', 'FORMIGA');
insert into risp (risp, city,city_fix) values('7ª RISP – Divinópolis', 'Igarantinga', 'IGARANTINGA');
insert into risp (risp, city,city_fix) values('7ª RISP – Divinópolis', 'Iguatama', 'IGUATAMA');
insert into risp (risp, city,city_fix) values('7ª RISP – Divinópolis', 'Itapecerica', 'ITAPECERICA');
insert into risp (risp, city,city_fix) values('7ª RISP – Divinópolis', 'Itatiaiucu', 'ITATIAIUCU');
insert into risp (risp, city,city_fix) values('7ª RISP – Divinópolis', 'Itaúna', 'ITAUNA');
insert into risp (risp, city,city_fix) values('7ª RISP – Divinópolis', 'Japaraíba', 'JAPARAIBA');
insert into risp (risp, city,city_fix) values('7ª RISP – Divinópolis', 'Lagoa da Prata', 'LAGOA DA PRATA');
insert into risp (risp, city,city_fix) values('7ª RISP – Divinópolis', 'Leandro Ferreira', 'LEANDRO FERREIRA');
insert into risp (risp, city,city_fix) values('7ª RISP – Divinópolis', 'Luz', 'LUZ');
insert into risp (risp, city,city_fix) values('7ª RISP – Divinópolis', 'Maravilhas', 'MARAVILHAS');
insert into risp (risp, city,city_fix) values('7ª RISP – Divinópolis', 'Martinho Campos', 'MARTINHO CAMPOS');
insert into risp (risp, city,city_fix) values('7ª RISP – Divinópolis', 'Medeiros', 'MEDEIROS');
insert into risp (risp, city,city_fix) values('7ª RISP – Divinópolis', 'Moema', 'MOEMA');
insert into risp (risp, city,city_fix) values('7ª RISP – Divinópolis', 'Morada Nova de Minas', 'MORADA NOVA DE MINAS');
insert into risp (risp, city,city_fix) values('7ª RISP – Divinópolis', 'Nova Serrana', 'NOVA SERRANA');
insert into risp (risp, city,city_fix) values('7ª RISP – Divinópolis', 'Onça de Pitangui', 'ONCA DE PITANGUI');
insert into risp (risp, city,city_fix) values('7ª RISP – Divinópolis', 'Paineiras', 'PAINEIRAS');
insert into risp (risp, city,city_fix) values('7ª RISP – Divinópolis', 'Pains', 'PAINS');
insert into risp (risp, city,city_fix) values('7ª RISP – Divinópolis', 'Papagaios', 'PAPAGAIOS');
insert into risp (risp, city,city_fix) values('7ª RISP – Divinópolis', 'Pará de Minas', 'PARA DE MINAS');
insert into risp (risp, city,city_fix) values('7ª RISP – Divinópolis', 'Pedra do Indaiá', 'PEDRA DO INDAIA');
insert into risp (risp, city,city_fix) values('7ª RISP – Divinópolis', 'Pequi', 'PEQUI');
insert into risp (risp, city,city_fix) values('7ª RISP – Divinópolis', 'Perdigão', 'PERDIGAO');
insert into risp (risp, city,city_fix) values('7ª RISP – Divinópolis', 'Pimenta', 'PIMENTA');
insert into risp (risp, city,city_fix) values('7ª RISP – Divinópolis', 'Pitangui', 'PITANGUI');
insert into risp (risp, city,city_fix) values('7ª RISP – Divinópolis', 'Pompeu', 'POMPEU');
insert into risp (risp, city,city_fix) values('7ª RISP – Divinópolis', 'Quartel Geral', 'QUARTEL GERAL');
insert into risp (risp, city,city_fix) values('7ª RISP – Divinópolis', 'Santo Antônio do Monte', 'SANTO ANTÔNIO DO MONTE');
insert into risp (risp, city,city_fix) values('7ª RISP – Divinópolis', 'São Fonçalo do Pará', 'SAO FONCALO DO PARA');
insert into risp (risp, city,city_fix) values('7ª RISP – Divinópolis', 'São José da Varginha', 'SAO JOSE DA VARGINHA');
insert into risp (risp, city,city_fix) values('7ª RISP – Divinópolis', 'São Sebastião do Oeste', 'SAO SEBASTIAO DO OESTE');
insert into risp (risp, city,city_fix) values('7ª RISP – Divinópolis', 'Serra da Saudade', 'SERRA DA SAUDADE');
insert into risp (risp, city,city_fix) values('7ª RISP – Divinópolis', 'Tapiraí', 'TAPIRAI');
insert into risp (risp, city,city_fix) values('8ª RISP – Governador Valadares', 'Aimorés', 'AIMORES');
insert into risp (risp, city,city_fix) values('8ª RISP – Governador Valadares', 'Alpercata', 'ALPERCATA');
insert into risp (risp, city,city_fix) values('8ª RISP – Governador Valadares', 'Alvarenga', 'ALVARENGA');
insert into risp (risp, city,city_fix) values('8ª RISP – Governador Valadares', 'Cantagalo', 'CANTAGALO');
insert into risp (risp, city,city_fix) values('8ª RISP – Governador Valadares', 'Capitão Andrade', 'CAPITAO ANDRADE');
insert into risp (risp, city,city_fix) values('8ª RISP – Governador Valadares', 'Central de Minas', 'CENTRAL DE MINAS');
insert into risp (risp, city,city_fix) values('8ª RISP – Governador Valadares', 'Coluna', 'COLUNA');
insert into risp (risp, city,city_fix) values('8ª RISP – Governador Valadares', 'Conceição do Mato Dentro', 'CONCEICAO DO MATO DENTRO');
insert into risp (risp, city,city_fix) values('8ª RISP – Governador Valadares', 'Congonhas do Norte', 'CONGONHAS DO NORTE');
insert into risp (risp, city,city_fix) values('8ª RISP – Governador Valadares', 'Conselheiro Pena', 'CONSELHEIRO PENA');
insert into risp (risp, city,city_fix) values('8ª RISP – Governador Valadares', 'Coroaci', 'COROACI');
insert into risp (risp, city,city_fix) values('8ª RISP – Governador Valadares', 'Cuparaque', 'CUPARAQUE');
insert into risp (risp, city,city_fix) values('8ª RISP – Governador Valadares', 'Divino das Laranjeiras', 'DIVINO DAS LARANJEIRAS');
insert into risp (risp, city,city_fix) values('8ª RISP – Governador Valadares', 'Divinolândia de Minas', 'DIVINOLANDIA DE MINAS');
insert into risp (risp, city,city_fix) values('8ª RISP – Governador Valadares', 'Dom Joaquim', 'DOM JOAQUIM');
insert into risp (risp, city,city_fix) values('8ª RISP – Governador Valadares', 'Dores de Guanhães', 'DORES DE GUANHAES');
insert into risp (risp, city,city_fix) values('8ª RISP – Governador Valadares', 'Engenheiro Caldas', 'ENGENHEIRO CALDAS');
insert into risp (risp, city,city_fix) values('8ª RISP – Governador Valadares', 'Fernandes Tourinho', 'FERNANDES TOURINHO');
insert into risp (risp, city,city_fix) values('8ª RISP – Governador Valadares', 'Frei Inocêncio', 'FREI INOCENCIO');
insert into risp (risp, city,city_fix) values('8ª RISP – Governador Valadares', 'Galileia', 'GALILEIA');
insert into risp (risp, city,city_fix) values('8ª RISP – Governador Valadares', 'Goiabeira', 'GOIABEIRA');
insert into risp (risp, city,city_fix) values('8ª RISP – Governador Valadares', 'Gonzaga', 'GONZAGA');
insert into risp (risp, city,city_fix) values('8ª RISP – Governador Valadares', 'Governador Valadares', 'GOVERNADOR VALADARES');
insert into risp (risp, city,city_fix) values('8ª RISP – Governador Valadares', 'Guanhães', 'GUANHAES');
insert into risp (risp, city,city_fix) values('8ª RISP – Governador Valadares', 'Itabirinha de Mantena', 'ITABIRINHA DE MANTENA');
insert into risp (risp, city,city_fix) values('8ª RISP – Governador Valadares', 'Itanhomi', 'ITANHOMI');
insert into risp (risp, city,city_fix) values('8ª RISP – Governador Valadares', 'Itueta', 'ITUETA');
insert into risp (risp, city,city_fix) values('8ª RISP – Governador Valadares', 'José Raydan', 'JOSE RAYDAN');
insert into risp (risp, city,city_fix) values('8ª RISP – Governador Valadares', 'Mantena', 'MANTENA');
insert into risp (risp, city,city_fix) values('8ª RISP – Governador Valadares', 'Marilac', 'MARILAC');
insert into risp (risp, city,city_fix) values('8ª RISP – Governador Valadares', 'Materlândia', 'MATERLANDIA');
insert into risp (risp, city,city_fix) values('8ª RISP – Governador Valadares', 'Mathias Lobato', 'MATHIAS LOBATO');
insert into risp (risp, city,city_fix) values('8ª RISP – Governador Valadares', 'Mendes Pimentel', 'MENDES PIMENTEL');
insert into risp (risp, city,city_fix) values('8ª RISP – Governador Valadares', 'Morro do Pilar', 'MORRO DO PILAR');
insert into risp (risp, city,city_fix) values('8ª RISP – Governador Valadares', 'Nacip Raydan', 'NACIP RAYDAN');
insert into risp (risp, city,city_fix) values('8ª RISP – Governador Valadares', 'Nova Belém', 'NOVA BELEM');
insert into risp (risp, city,city_fix) values('8ª RISP – Governador Valadares', 'Paulistas', 'PAULISTAS');
insert into risp (risp, city,city_fix) values('8ª RISP – Governador Valadares', 'Pecanha', 'PECANHA');
insert into risp (risp, city,city_fix) values('8ª RISP – Governador Valadares', 'Periquito', 'PERIQUITO');
insert into risp (risp, city,city_fix) values('8ª RISP – Governador Valadares', 'Resplendor', 'RESPLENDOR');
insert into risp (risp, city,city_fix) values('8ª RISP – Governador Valadares', 'Rio Vermelho', 'RIO VERMELHO');
insert into risp (risp, city,city_fix) values('8ª RISP – Governador Valadares', 'Sabinópolis', 'SABINOPOLIS');
insert into risp (risp, city,city_fix) values('8ª RISP – Governador Valadares', 'Santa Efigênia de Minas', 'SANTA EFIGENIA DE MINAS');
insert into risp (risp, city,city_fix) values('8ª RISP – Governador Valadares', 'Santa Maria do Suacui', 'SANTA MARIA DO SUACUI');
insert into risp (risp, city,city_fix) values('8ª RISP – Governador Valadares', 'Santa Rita do Itueto', 'SANTA RITA DO ITUETO');
insert into risp (risp, city,city_fix) values('8ª RISP – Governador Valadares', 'Santo Antônio do Rio Abaixo', 'SANTO ANTÔNIO DO RIO ABAIXO');
insert into risp (risp, city,city_fix) values('8ª RISP – Governador Valadares', 'São Félix de Minas', 'SAO FELIX DE MINAS');
insert into risp (risp, city,city_fix) values('8ª RISP – Governador Valadares', 'São Geraldo da Piedade', 'SAO GERALDO DA PIEDADE');
insert into risp (risp, city,city_fix) values('8ª RISP – Governador Valadares', 'São Geraldo do Baixio', 'SAO GERALDO DO BAIXIO');
insert into risp (risp, city,city_fix) values('8ª RISP – Governador Valadares', 'São João do Manteninha', 'SAO JOAO DO MANTENINHA');
insert into risp (risp, city,city_fix) values('8ª RISP – Governador Valadares', 'São João Evangelista', 'SAO JOAO EVANGELISTA');
insert into risp (risp, city,city_fix) values('8ª RISP – Governador Valadares', 'São José da Safira', 'SAO JOSE DA SAFIRA');
insert into risp (risp, city,city_fix) values('8ª RISP – Governador Valadares', 'São José do Jacuri', 'SAO JOSE DO JACURI');
insert into risp (risp, city,city_fix) values('8ª RISP – Governador Valadares', 'São Pedro do Suacui', 'SAO PEDRO DO SUACUI');
insert into risp (risp, city,city_fix) values('8ª RISP – Governador Valadares', 'São Sebastião do Maranhão', 'SAO SEBASTIAO DO MARANHAO');
insert into risp (risp, city,city_fix) values('8ª RISP – Governador Valadares', 'São Sebastião do Rio Preto', 'SAO SEBASTIAO DO RIO PRETO');
insert into risp (risp, city,city_fix) values('8ª RISP – Governador Valadares', 'Sardoa', 'SARDOA');
insert into risp (risp, city,city_fix) values('8ª RISP – Governador Valadares', 'Senhora do Porto', 'SENHORA DO PORTO');
insert into risp (risp, city,city_fix) values('8ª RISP – Governador Valadares', 'Sobrália', 'SOBRALIA');
insert into risp (risp, city,city_fix) values('8ª RISP – Governador Valadares', 'Tarumirim', 'TARUMIRIM');
insert into risp (risp, city,city_fix) values('8ª RISP – Governador Valadares', 'Tumiritinga', 'TUMIRITINGA');
insert into risp (risp, city,city_fix) values('8ª RISP – Governador Valadares', 'Virginópolis', 'VIRGINOPOLIS');
insert into risp (risp, city,city_fix) values('8ª RISP – Governador Valadares', 'Virgolândia', 'VIRGOLANDIA');
insert into risp (risp, city,city_fix) values('9ª RISP – Uberlândia', 'Araguari', 'ARAGUARI');
insert into risp (risp, city,city_fix) values('9ª RISP – Uberlândia', 'Arapora', 'ARAPORA');
insert into risp (risp, city,city_fix) values('9ª RISP – Uberlândia', 'Cachoeira Dourada', 'CACHOEIRA DOURADA');
insert into risp (risp, city,city_fix) values('9ª RISP – Uberlândia', 'Canapólis', 'CANAPOLIS');
insert into risp (risp, city,city_fix) values('9ª RISP – Uberlândia', 'Capinópolis', 'CAPINOPOLIS');
insert into risp (risp, city,city_fix) values('9ª RISP – Uberlândia', 'Cascalho Rico', 'CASCALHO RICO');
insert into risp (risp, city,city_fix) values('9ª RISP – Uberlândia', 'Centralina', 'CENTRALINA');
insert into risp (risp, city,city_fix) values('9ª RISP – Uberlândia', 'Estrela do Sul', 'ESTRELA DO SUL');
insert into risp (risp, city,city_fix) values('9ª RISP – Uberlândia', 'Grupiara', 'GRUPIARA');
insert into risp (risp, city,city_fix) values('9ª RISP – Uberlândia', 'Gurinhata', 'GURINHATA');
insert into risp (risp, city,city_fix) values('9ª RISP – Uberlândia', 'Indianópolis', 'INDIANOPOLIS');
insert into risp (risp, city,city_fix) values('9ª RISP – Uberlândia', 'Ipiacu', 'IPIACU');
insert into risp (risp, city,city_fix) values('9ª RISP – Uberlândia', 'Ituiutaba', 'ITUIUTABA');
insert into risp (risp, city,city_fix) values('9ª RISP – Uberlândia', 'Monte Alegre de Minas', 'MONTE ALEGRE DE MINAS');
insert into risp (risp, city,city_fix) values('9ª RISP – Uberlândia', 'Prata', 'PRATA');
insert into risp (risp, city,city_fix) values('9ª RISP – Uberlândia', 'Santa Vitória', 'SANTA VITORIA');
insert into risp (risp, city,city_fix) values('9ª RISP – Uberlândia', 'Tupaciguara', 'TUPACIGUARA');
insert into risp (risp, city,city_fix) values('9ª RISP – Uberlândia', 'Uberlândia', 'UBERLANDIA');
insert into risp (risp, city,city_fix) values('10ª RISP – Patos de Minas', 'Abadia dos Dourados', 'ABADIA DOS DOURADOS');
insert into risp (risp, city,city_fix) values('10ª RISP – Patos de Minas', 'Arapuá', 'ARAPUA');
insert into risp (risp, city,city_fix) values('10ª RISP – Patos de Minas', 'Carmo do Parnaíba', 'CARMO DO PARNAIBA');
insert into risp (risp, city,city_fix) values('10ª RISP – Patos de Minas', 'Coromandel', 'COROMANDEL');
insert into risp (risp, city,city_fix) values('10ª RISP – Patos de Minas', 'Cruzeiro da Fortaleza', 'CRUZEIRO DA FORTALEZA');
insert into risp (risp, city,city_fix) values('10ª RISP – Patos de Minas', 'Douradoquara', 'DOURADOQUARA');
insert into risp (risp, city,city_fix) values('10ª RISP – Patos de Minas', 'Guimarania', 'GUIMARANIA');
insert into risp (risp, city,city_fix) values('10ª RISP – Patos de Minas', 'Iraí de Minas', 'IRAI DE MINAS');
insert into risp (risp, city,city_fix) values('10ª RISP – Patos de Minas', 'Lagamar', 'LAGAMAR');
insert into risp (risp, city,city_fix) values('10ª RISP – Patos de Minas', 'Lagoa Formosa', 'LAGOA FORMOSA');
insert into risp (risp, city,city_fix) values('10ª RISP – Patos de Minas', 'Lagoa Grande', 'LAGOA GRANDE');
insert into risp (risp, city,city_fix) values('10ª RISP – Patos de Minas', 'Matutina', 'MATUTINA');
insert into risp (risp, city,city_fix) values('10ª RISP – Patos de Minas', 'Monte Carmelo', 'MONTE CARMELO');
insert into risp (risp, city,city_fix) values('10ª RISP – Patos de Minas', 'Patos de Minas', 'PATOS DE MINAS');
insert into risp (risp, city,city_fix) values('10ª RISP – Patos de Minas', 'Patrocínio', 'PATROCINIO');
insert into risp (risp, city,city_fix) values('10ª RISP – Patos de Minas', 'Presidente Olegário', 'PRESIDENTE OLEGARIO');
insert into risp (risp, city,city_fix) values('10ª RISP – Patos de Minas', 'Rio Paranaíba', 'RIO PARANAIBA');
insert into risp (risp, city,city_fix) values('10ª RISP – Patos de Minas', 'Romaria', 'ROMARIA');
insert into risp (risp, city,city_fix) values('10ª RISP – Patos de Minas', 'São Gonçalo do Abaete', 'SAO GONCALO DO ABAETE');
insert into risp (risp, city,city_fix) values('10ª RISP – Patos de Minas', 'São Gotardo', 'SAO GOTARDO');
insert into risp (risp, city,city_fix) values('10ª RISP – Patos de Minas', 'Serra do Salitre', 'SERRA DO SALITRE');
insert into risp (risp, city,city_fix) values('10ª RISP – Patos de Minas', 'Tiros', 'TIROS');
insert into risp (risp, city,city_fix) values('10ª RISP – Patos de Minas', 'Varjão de Minas', 'VARJAO DE MINAS');
insert into risp (risp, city,city_fix) values('11ª RISP – Montes Claros', 'Berizal', 'BERIZAL');
insert into risp (risp, city,city_fix) values('11ª RISP – Montes Claros', 'Bocaiuva', 'BOCAIUVA');
insert into risp (risp, city,city_fix) values('11ª RISP – Montes Claros', 'Bonito de Minas', 'BONITO DE MINAS');
insert into risp (risp, city,city_fix) values('11ª RISP – Montes Claros', 'Botumirim', 'BOTUMIRIM');
insert into risp (risp, city,city_fix) values('11ª RISP – Montes Claros', 'Brasília de Minas', 'BRASILIA DE MINAS');
insert into risp (risp, city,city_fix) values('11ª RISP – Montes Claros', 'Campo Azul', 'CAMPO AZUL');
insert into risp (risp, city,city_fix) values('11ª RISP – Montes Claros', 'Capitão Enéas', 'CAPITAO ENEAS');
insert into risp (risp, city,city_fix) values('11ª RISP – Montes Claros', 'Catuti', 'CATUTI');
insert into risp (risp, city,city_fix) values('11ª RISP – Montes Claros', 'Claro dos Poções', 'CLARO DOS POCOES');
insert into risp (risp, city,city_fix) values('11ª RISP – Montes Claros', 'Cônego Marinho', 'CÔNEGO MARINHO');
insert into risp (risp, city,city_fix) values('11ª RISP – Montes Claros', 'Coração de Jesus', 'CORACAO DE JESUS');
insert into risp (risp, city,city_fix) values('11ª RISP – Montes Claros', 'Cristália', 'CRISTALIA');
insert into risp (risp, city,city_fix) values('11ª RISP – Montes Claros', 'Curral de Dentro', 'CURRAL DE DENTRO');
insert into risp (risp, city,city_fix) values('11ª RISP – Montes Claros', 'Engenheiro Navarro', 'ENGENHEIRO NAVARRO');
insert into risp (risp, city,city_fix) values('11ª RISP – Montes Claros', 'Espinosa', 'ESPINOSA');
insert into risp (risp, city,city_fix) values('11ª RISP – Montes Claros', 'Francisco Dumont', 'FRANCISCO DUMONT');
insert into risp (risp, city,city_fix) values('11ª RISP – Montes Claros', 'Francisco Sá', 'FRANCISCO SA');
insert into risp (risp, city,city_fix) values('11ª RISP – Montes Claros', 'Fruta de Leite', 'FRUTA DE LEITE');
insert into risp (risp, city,city_fix) values('11ª RISP – Montes Claros', 'Gameleiras', 'GAMELEIRAS');
insert into risp (risp, city,city_fix) values('11ª RISP – Montes Claros', 'Glaucilândia', 'GLAUCILANDIA');
insert into risp (risp, city,city_fix) values('11ª RISP – Montes Claros', 'Grão Mogol', 'GRAO MOGOL');
insert into risp (risp, city,city_fix) values('11ª RISP – Montes Claros', 'Guaraciama', 'GUARACIAMA');
insert into risp (risp, city,city_fix) values('11ª RISP – Montes Claros', 'Ibiaí', 'IBIAI');
insert into risp (risp, city,city_fix) values('11ª RISP – Montes Claros', 'Ibiracatu', 'IBIRACATU');
insert into risp (risp, city,city_fix) values('11ª RISP – Montes Claros', 'Icaraí de Minas', 'ICARAI DE MINAS');
insert into risp (risp, city,city_fix) values('11ª RISP – Montes Claros', 'Indaiabira', 'INDAIABIRA');
insert into risp (risp, city,city_fix) values('11ª RISP – Montes Claros', 'Itacambira', 'ITACAMBIRA');
insert into risp (risp, city,city_fix) values('11ª RISP – Montes Claros', 'Itacarambi', 'ITACARAMBI');
insert into risp (risp, city,city_fix) values('11ª RISP – Montes Claros', 'Jaíba', 'JAIBA');
insert into risp (risp, city,city_fix) values('11ª RISP – Montes Claros', 'Janaúba', 'JANAUBA');
insert into risp (risp, city,city_fix) values('11ª RISP – Montes Claros', 'Januária', 'JANUARIA');
insert into risp (risp, city,city_fix) values('11ª RISP – Montes Claros', 'Japonvar', 'JAPONVAR');
insert into risp (risp, city,city_fix) values('11ª RISP – Montes Claros', 'Josenópolis', 'JOSENOPOLIS');
insert into risp (risp, city,city_fix) values('11ª RISP – Montes Claros', 'Juramento', 'JURAMENTO');
insert into risp (risp, city,city_fix) values('11ª RISP – Montes Claros', 'Juvenilia', 'JUVENILIA');
insert into risp (risp, city,city_fix) values('11ª RISP – Montes Claros', 'Lagoa dos Patos', 'LAGOA DOS PATOS');
insert into risp (risp, city,city_fix) values('11ª RISP – Montes Claros', 'Lontra', 'LONTRA');
insert into risp (risp, city,city_fix) values('11ª RISP – Montes Claros', 'Luislândia', 'LUISLANDIA');
insert into risp (risp, city,city_fix) values('11ª RISP – Montes Claros', 'Mamonas', 'MAMONAS');
insert into risp (risp, city,city_fix) values('11ª RISP – Montes Claros', 'Manga', 'MANGA');
insert into risp (risp, city,city_fix) values('11ª RISP – Montes Claros', 'Matias Cardoso', 'MATIAS CARDOSO');
insert into risp (risp, city,city_fix) values('11ª RISP – Montes Claros', 'Mato Verde', 'MATO VERDE');
insert into risp (risp, city,city_fix) values('11ª RISP – Montes Claros', 'Mirabela', 'MIRABELA');
insert into risp (risp, city,city_fix) values('11ª RISP – Montes Claros', 'Miravânia', 'MIRAVANIA');
insert into risp (risp, city,city_fix) values('11ª RISP – Montes Claros', 'Montalvania', 'MONTALVANIA');
insert into risp (risp, city,city_fix) values('11ª RISP – Montes Claros', 'Monte Azul', 'MONTE AZUL');
insert into risp (risp, city,city_fix) values('11ª RISP – Montes Claros', 'Montes Claros', 'MONTES CLAROS');
insert into risp (risp, city,city_fix) values('11ª RISP – Montes Claros', 'Montezuma', 'MONTEZUMA');
insert into risp (risp, city,city_fix) values('11ª RISP – Montes Claros', 'Ninheira', 'NINHEIRA');
insert into risp (risp, city,city_fix) values('11ª RISP – Montes Claros', 'Novorizonte', 'NOVORIZONTE');
insert into risp (risp, city,city_fix) values('11ª RISP – Montes Claros', 'Olhos d’Água', 'OLHOS D’AGUA');
insert into risp (risp, city,city_fix) values('11ª RISP – Montes Claros', 'Padre Carvalho', 'PADRE CARVALHO');
insert into risp (risp, city,city_fix) values('11ª RISP – Montes Claros', 'Pai Pedro', 'PAI PEDRO');
insert into risp (risp, city,city_fix) values('11ª RISP – Montes Claros', 'Patis', 'PATIS');
insert into risp (risp, city,city_fix) values('11ª RISP – Montes Claros', 'Pedras de Maria da Cruz', 'PEDRAS DE MARIA DA CRUZ');
insert into risp (risp, city,city_fix) values('11ª RISP – Montes Claros', 'Pintopólis', 'PINTOPOLIS');
insert into risp (risp, city,city_fix) values('11ª RISP – Montes Claros', 'Ponto Chique', 'PONTO CHIQUE');
insert into risp (risp, city,city_fix) values('11ª RISP – Montes Claros', 'Porteirinha', 'PORTEIRINHA');
insert into risp (risp, city,city_fix) values('11ª RISP – Montes Claros', 'Riacho dos Machados', 'RIACHO DOS MACHADOS');
insert into risp (risp, city,city_fix) values('11ª RISP – Montes Claros', 'Rio Pardo de Minas', 'RIO PARDO DE MINAS');
insert into risp (risp, city,city_fix) values('11ª RISP – Montes Claros', 'Rubelita', 'RUBELITA');
insert into risp (risp, city,city_fix) values('11ª RISP – Montes Claros', 'Salinas', 'SALINAS');
insert into risp (risp, city,city_fix) values('11ª RISP – Montes Claros', 'Santa Cruz de Salinas', 'SANTA CRUZ DE SALINAS');
insert into risp (risp, city,city_fix) values('11ª RISP – Montes Claros', 'Santo Antônio do Retiro', 'SANTO ANTÔNIO DO RETIRO');
insert into risp (risp, city,city_fix) values('11ª RISP – Montes Claros', 'São Francisco', 'SAO FRANCISCO');
insert into risp (risp, city,city_fix) values('11ª RISP – Montes Claros', 'São João da Lagoa', 'SAO JOAO DA LAGOA');
insert into risp (risp, city,city_fix) values('11ª RISP – Montes Claros', 'São João da Ponte', 'SAO JOAO DA PONTE');
insert into risp (risp, city,city_fix) values('11ª RISP – Montes Claros', 'São João das Missões', 'SAO JOAO DAS MISSOES');
insert into risp (risp, city,city_fix) values('11ª RISP – Montes Claros', 'São João do Pacuí', 'SAO JOAO DO PACUI');
insert into risp (risp, city,city_fix) values('11ª RISP – Montes Claros', 'São João do Paraíso', 'SAO JOAO DO PARAISO');
insert into risp (risp, city,city_fix) values('11ª RISP – Montes Claros', 'Serranópolis de Minas', 'SERRANOPOLIS DE MINAS');
insert into risp (risp, city,city_fix) values('11ª RISP – Montes Claros', 'Taiobeiras', 'TAIOBEIRAS');
insert into risp (risp, city,city_fix) values('11ª RISP – Montes Claros', 'Ubaí', 'UBAI');
insert into risp (risp, city,city_fix) values('11ª RISP – Montes Claros', 'Vargem Grande do Rio Pardo', 'VARGEM GRANDE DO RIO PARDO');
insert into risp (risp, city,city_fix) values('11ª RISP – Montes Claros', 'Varzelândia', 'VARZELANDIA');
insert into risp (risp, city,city_fix) values('11ª RISP – Montes Claros', 'Verdelândia', 'VERDELANDIA');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'Abre Campo', 'ABRE CAMPO');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'Acaiacá', 'ACAIACA');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'Acucena', 'ACUCENA');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'Alto Caparão', 'ALTO CAPARAO');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'Alto Jequitibá', 'ALTO JEQUITIBA');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'Alvinópolis', 'ALVINOPOLIS');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'Amparo da Serra', 'AMPARO DA SERRA');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'Antônio Dias', 'ANTÔNIO DIAS');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'Barão de Cocais', 'BARAO DE COCAIS');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'Barra Longa', 'BARRA LONGA');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'Bela Vista de Minas', 'BELA VISTA DE MINAS');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'Belo Oriente', 'BELO ORIENTE');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'Bom Jesus do Amparo', 'BOM JESUS DO AMPARO');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'Bom Jesus do Galho', 'BOM JESUS DO GALHO');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'Braúnas', 'BRAUNAS');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'Bugre', 'BUGRE');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'Caiana', 'CAIANA');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'Caparão', 'CAPARAO');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'Caputira', 'CAPUTIRA');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'Caratinga', 'CARATINGA');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'Carmésia', 'CARMESIA');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'Catas Altas', 'CATAS ALTAS');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'Chalé', 'CHALE');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'Conceição de Ipanema', 'CONCEICAO DE IPANEMA');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'Coronel Fabriciano', 'CORONEL FABRICIANO');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'Córrego Novo', 'CORREGO NOVO');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'Dionísio', 'DIONISIO');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'Dom Cavati', 'DOM CAVATI');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'Dom Silvério', 'DOM SILVERIO');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'Durande', 'DURANDE');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'Entre Folhas', 'ENTRE FOLHAS');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'Espera Feliz', 'ESPERA FELIZ');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'Ferros', 'FERROS');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'Guaraciaba', 'GUARACIABA');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'Iapu', 'IAPU');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'Imbé de Minas', 'IMBE DE MINAS');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'Inhapim', 'INHAPIM');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'Ipaba', 'IPABA');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'Ipanema', 'IPANEMA');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'Ipatinga', 'IPATINGA');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'Itabira', 'ITABIRA');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'Itambé do Mato Dentro', 'ITAMBE DO MATO DENTRO');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'Jaguaraçu', 'JAGUARACU');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'Jequeri', 'JEQUERI');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'Joanésia', 'JOANESIA');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'João Monlevade', 'JOAO MONLEVADE');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'Lajinha', 'LAJINHA');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'Luisburgo', 'LUISBURGO');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'Manhuaçu', 'MANHUACU');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'Manhumirim', 'MANHUMIRIM');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'Marlieria', 'MARLIERIA');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'Martins Soares', 'MARTINS SOARES');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'Matipo', 'MATIPO');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'Mesquita', 'MESQUITA');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'Mutum', 'MUTUM');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'Naque', 'NAQUE');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'Nova Era', 'NOVA ERA');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'Oratórios', 'ORATORIOS');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'Passabem', 'PASSABEM');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'Pedra Bonita', 'PEDRA BONITA');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'Piedade de Caratinga', 'PIEDADE DE CARATINGA');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'Piedade de Ponte Nova', 'PIEDADE DE PONTE NOVA');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'Pingo d’Água', 'PINGO D’AGUA');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'Pocrane', 'POCRANE');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'Ponte Nova', 'PONTE NOVA');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'Raul Soares', 'RAUL SOARES');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'Reduto', 'REDUTO');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'Rio Casca', 'RIO CASCA');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'Rio Doce', 'RIO DOCE');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'Rio Piracicaba', 'RIO PIRACICABA');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'Santa Bárbara', 'SANTA BARBARA');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'Santa Bárbara do Leste', 'SANTA BARBARA DO LESTE');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'Santa Cruz do Escalvado', 'SANTA CRUZ DO ESCALVADO');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'Santa Margarida', 'SANTA MARGARIDA');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'Santa Maria de Itabira', 'SANTA MARIA DE ITABIRA');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'Santa Rita de Minas', 'SANTA RITA DE MINAS');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'Santana do Manhuaçu', 'SANTANA DO MANHUACU');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'Santana do Paraíso', 'SANTANA DO PARAISO');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'Santo Antônio do Grama', 'SANTO ANTÔNIO DO GRAMA');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'São Domingos das Dores', 'SAO DOMINGOS DAS DORES');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'São Domingos do Prata', 'SAO DOMINGOS DO PRATA');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'São Gonçalo do Rio Abaixo', 'SAO GONCALO DO RIO ABAIXO');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'São João do Manhuaçu', 'SAO JOAO DO MANHUACU');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'São João do Oriente', 'SAO JOAO DO ORIENTE');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'São José do Goiabal', 'SAO JOSE DO GOIABAL');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'São José do Mantimento', 'SAO JOSE DO MANTIMENTO');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'São Pedro dos Ferros', 'SAO PEDRO DOS FERROS');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'São Sebastião do Anta', 'SAO SEBASTIAO DO ANTA');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'Sem Peixe', 'SEM PEIXE');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'Sericita', 'SERICITA');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'Simonésia', 'SIMONESIA');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'Taparuba', 'TAPARUBA');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'Timóteo', 'TIMOTEO');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'Ubaporanga', 'UBAPORANGA');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'Urucânia', 'URUCANIA');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'Vargem Alegre', 'VARGEM ALEGRE');
insert into risp (risp, city,city_fix) values('12ª RISP – Ipatinga', 'Vermelho Novo', 'VERMELHO NOVO');
insert into risp (risp, city,city_fix) values('13ª RISP – Barbacena', 'Alfredo Vasconcelos', 'ALFREDO VASCONCELOS');
insert into risp (risp, city,city_fix) values('13ª RISP – Barbacena', 'Alto Rio Doce', 'ALTO RIO DOCE');
insert into risp (risp, city,city_fix) values('13ª RISP – Barbacena', 'Andrelândia', 'ANDRELANDIA');
insert into risp (risp, city,city_fix) values('13ª RISP – Barbacena', 'Antônio Carlos', 'ANTÔNIO CARLOS');
insert into risp (risp, city,city_fix) values('13ª RISP – Barbacena', 'Aracitaba', 'ARACITABA');
insert into risp (risp, city,city_fix) values('13ª RISP – Barbacena', 'Arantina', 'ARANTINA');
insert into risp (risp, city,city_fix) values('13ª RISP – Barbacena', 'Barbacena', 'BARBACENA');
insert into risp (risp, city,city_fix) values('13ª RISP – Barbacena', 'Barroso', 'BARROSO');
insert into risp (risp, city,city_fix) values('13ª RISP – Barbacena', 'Belo Vale', 'BELO VALE');
insert into risp (risp, city,city_fix) values('13ª RISP – Barbacena', 'Bias Fortes', 'BIAS FORTES');
insert into risp (risp, city,city_fix) values('13ª RISP – Barbacena', 'Bom Jardim de Minas', 'BOM JARDIM DE MINAS');
insert into risp (risp, city,city_fix) values('13ª RISP – Barbacena', 'Capela Nova', 'CAPELA NOVA');
insert into risp (risp, city,city_fix) values('13ª RISP – Barbacena', 'Caranaíba', 'CARANAIBA');
insert into risp (risp, city,city_fix) values('13ª RISP – Barbacena', 'Carandaí', 'CARANDAI');
insert into risp (risp, city,city_fix) values('13ª RISP – Barbacena', 'Casa Grande', 'CASA GRANDE');
insert into risp (risp, city,city_fix) values('13ª RISP – Barbacena', 'Catas Altas da Noruega', 'CATAS ALTAS DA NORUEGA');
insert into risp (risp, city,city_fix) values('13ª RISP – Barbacena', 'Cipotânea', 'CIPOTANEA');
insert into risp (risp, city,city_fix) values('13ª RISP – Barbacena', 'Conceição da Barra de Minas', 'CONCEICAO DA BARRA DE MINAS');
insert into risp (risp, city,city_fix) values('13ª RISP – Barbacena', 'Congonhas', 'CONGONHAS');
insert into risp (risp, city,city_fix) values('13ª RISP – Barbacena', 'Conselheiro Lafaiete', 'CONSELHEIRO LAFAIETE');
insert into risp (risp, city,city_fix) values('13ª RISP – Barbacena', 'Coronel Xavier Chaves', 'CORONEL XAVIER CHAVES');
insert into risp (risp, city,city_fix) values('13ª RISP – Barbacena', 'Cristiano Otoni', 'CRISTIANO OTONI');
insert into risp (risp, city,city_fix) values('13ª RISP – Barbacena', 'Desterro de Entre Rios', 'DESTERRO DE ENTRE RIOS');
insert into risp (risp, city,city_fix) values('13ª RISP – Barbacena', 'Desterro do Melo', 'DESTERRO DO MELO');
insert into risp (risp, city,city_fix) values('13ª RISP – Barbacena', 'Dores de Campos', 'DORES DE CAMPOS');
insert into risp (risp, city,city_fix) values('13ª RISP – Barbacena', 'Entre Rios de Minas', 'ENTRE RIOS DE MINAS');
insert into risp (risp, city,city_fix) values('13ª RISP – Barbacena', 'Ewbank da Câmara', 'EWBANK DA CAMARA');
insert into risp (risp, city,city_fix) values('13ª RISP – Barbacena', 'Ibertioga', 'IBERTIOGA');
insert into risp (risp, city,city_fix) values('13ª RISP – Barbacena', 'Itaverava', 'ITAVERAVA');
insert into risp (risp, city,city_fix) values('13ª RISP – Barbacena', 'Jeceaba', 'JECEABA');
insert into risp (risp, city,city_fix) values('13ª RISP – Barbacena', 'Lagoa Dourada', 'LAGOA DOURADA');
insert into risp (risp, city,city_fix) values('13ª RISP – Barbacena', 'Lamim', 'LAMIM');
insert into risp (risp, city,city_fix) values('13ª RISP – Barbacena', 'Madre de Deus de Minas', 'MADRE DE DEUS DE MINAS');
insert into risp (risp, city,city_fix) values('13ª RISP – Barbacena', 'Moeda', 'MOEDA');
insert into risp (risp, city,city_fix) values('13ª RISP – Barbacena', 'Nazareno', 'NAZARENO');
insert into risp (risp, city,city_fix) values('13ª RISP – Barbacena', 'Oliveira Fortes', 'OLIVEIRA FORTES');
insert into risp (risp, city,city_fix) values('13ª RISP – Barbacena', 'Ouro Branco', 'OURO BRANCO');
insert into risp (risp, city,city_fix) values('13ª RISP – Barbacena', 'Paiva', 'PAIVA');
insert into risp (risp, city,city_fix) values('13ª RISP – Barbacena', 'Piedade do Rio Grande', 'PIEDADE DO RIO GRANDE');
insert into risp (risp, city,city_fix) values('13ª RISP – Barbacena', 'Piranga', 'PIRANGA');
insert into risp (risp, city,city_fix) values('13ª RISP – Barbacena', 'Ponto Firme', 'PONTO FIRME');
insert into risp (risp, city,city_fix) values('13ª RISP – Barbacena', 'Prados', 'PRADOS');
insert into risp (risp, city,city_fix) values('13ª RISP – Barbacena', 'Presidente Bernardes', 'PRESIDENTE BERNARDES');
insert into risp (risp, city,city_fix) values('13ª RISP – Barbacena', 'Queluzito', 'QUELUZITO');
insert into risp (risp, city,city_fix) values('13ª RISP – Barbacena', 'Resende Costa', 'RESENDE COSTA');
insert into risp (risp, city,city_fix) values('13ª RISP – Barbacena', 'Ressaquinha', 'RESSAQUINHA');
insert into risp (risp, city,city_fix) values('13ª RISP – Barbacena', 'Rio Espera', 'RIO ESPERA');
insert into risp (risp, city,city_fix) values('13ª RISP – Barbacena', 'Ritapólis', 'RITAPOLIS');
insert into risp (risp, city,city_fix) values('13ª RISP – Barbacena', 'Santa Bárbara do Tugurio', 'SANTA BARBARA DO TUGURIO');
insert into risp (risp, city,city_fix) values('13ª RISP – Barbacena', 'Santa Cruz de Minas', 'SANTA CRUZ DE MINAS');
insert into risp (risp, city,city_fix) values('13ª RISP – Barbacena', 'Santa Rita de Ibitipoca', 'SANTA RITA DE IBITIPOCA');
insert into risp (risp, city,city_fix) values('13ª RISP – Barbacena', 'Santana do Garambéu', 'SANTANA DO GARAMBEU');
insert into risp (risp, city,city_fix) values('13ª RISP – Barbacena', 'Santana dos Montes', 'SANTANA DOS MONTES');
insert into risp (risp, city,city_fix) values('13ª RISP – Barbacena', 'Santos Dumont', 'SANTOS DUMONT');
insert into risp (risp, city,city_fix) values('13ª RISP – Barbacena', 'São Brás do Suacuí', 'SAO BRAS DO SUACUI');
insert into risp (risp, city,city_fix) values('13ª RISP – Barbacena', 'São João Del Rei', 'SAO JOAO DEL REI');
insert into risp (risp, city,city_fix) values('13ª RISP – Barbacena', 'São Tiago', 'SAO TIAGO');
insert into risp (risp, city,city_fix) values('13ª RISP – Barbacena', 'São Vicente de Minas', 'SAO VICENTE DE MINAS');
insert into risp (risp, city,city_fix) values('13ª RISP – Barbacena', 'Senhora de Oliveira', 'SENHORA DE OLIVEIRA');
insert into risp (risp, city,city_fix) values('13ª RISP – Barbacena', 'Senhora dos Remédios', 'SENHORA DOS REMEDIOS');
insert into risp (risp, city,city_fix) values('13ª RISP – Barbacena', 'Tiradentes', 'TIRADENTES');
insert into risp (risp, city,city_fix) values('14ª RISP – Curvelo', 'Água Boa', 'AGUA BOA');
insert into risp (risp, city,city_fix) values('14ª RISP – Curvelo', 'Alvorada de Minas', 'ALVORADA DE MINAS');
insert into risp (risp, city,city_fix) values('14ª RISP – Curvelo', 'Angelândia', 'ANGELANDIA');
insert into risp (risp, city,city_fix) values('14ª RISP – Curvelo', 'Aricanduva', 'ARICANDUVA');
insert into risp (risp, city,city_fix) values('14ª RISP – Curvelo', 'Augusto de Lima', 'AUGUSTO DE LIMA');
insert into risp (risp, city,city_fix) values('14ª RISP – Curvelo', 'Berilo', 'BERILO');
insert into risp (risp, city,city_fix) values('14ª RISP – Curvelo', 'Buenópolis', 'BUENOPOLIS');
insert into risp (risp, city,city_fix) values('14ª RISP – Curvelo', 'Buritizeiro', 'BURITIZEIRO');
insert into risp (risp, city,city_fix) values('14ª RISP – Curvelo', 'Capelinha', 'CAPELINHA');
insert into risp (risp, city,city_fix) values('14ª RISP – Curvelo', 'Carbonita', 'CARBONITA');
insert into risp (risp, city,city_fix) values('14ª RISP – Curvelo', 'Chapada do Norte', 'CHAPADA DO NORTE');
insert into risp (risp, city,city_fix) values('14ª RISP – Curvelo', 'Corinto', 'CORINTO');
insert into risp (risp, city,city_fix) values('14ª RISP – Curvelo', 'Couto de Magalhães de Minas', 'COUTO DE MAGALHAES DE MINAS');
insert into risp (risp, city,city_fix) values('14ª RISP – Curvelo', 'Curvelo', 'CURVELO');
insert into risp (risp, city,city_fix) values('14ª RISP – Curvelo', 'Datas', 'DATAS');
insert into risp (risp, city,city_fix) values('14ª RISP – Curvelo', 'Diamantina', 'DIAMANTINA');
insert into risp (risp, city,city_fix) values('14ª RISP – Curvelo', 'Felício dos Santos', 'FELICIO DOS SANTOS');
insert into risp (risp, city,city_fix) values('14ª RISP – Curvelo', 'Felixlândia', 'FELIXLANDIA');
insert into risp (risp, city,city_fix) values('14ª RISP – Curvelo', 'Francisco Badaro', 'FRANCISCO BADARO');
insert into risp (risp, city,city_fix) values('14ª RISP – Curvelo', 'Gouvéia', 'GOUVEIA');
insert into risp (risp, city,city_fix) values('14ª RISP – Curvelo', 'Inimutaba', 'INIMUTABA');
insert into risp (risp, city,city_fix) values('14ª RISP – Curvelo', 'Itamarandiba', 'ITAMARANDIBA');
insert into risp (risp, city,city_fix) values('14ª RISP – Curvelo', 'Jenipapo de Minas', 'JENIPAPO DE MINAS');
insert into risp (risp, city,city_fix) values('14ª RISP – Curvelo', 'Jequitaí', 'JEQUITAI');
insert into risp (risp, city,city_fix) values('14ª RISP – Curvelo', 'Joaquim Felício', 'JOAQUIM FELICIO');
insert into risp (risp, city,city_fix) values('14ª RISP – Curvelo', 'José Gonçalves de Minas', 'JOSE GONCALVES DE MINAS');
insert into risp (risp, city,city_fix) values('14ª RISP – Curvelo', 'Lassance', 'LASSANCE');
insert into risp (risp, city,city_fix) values('14ª RISP – Curvelo', 'Leme do Prado', 'LEME DO PRADO');
insert into risp (risp, city,city_fix) values('14ª RISP – Curvelo', 'Minas Novas', 'MINAS NOVAS');
insert into risp (risp, city,city_fix) values('14ª RISP – Curvelo', 'Monjolos', 'MONJOLOS');
insert into risp (risp, city,city_fix) values('14ª RISP – Curvelo', 'Morro da Garça', 'MORRO DA GARCA');
insert into risp (risp, city,city_fix) values('14ª RISP – Curvelo', 'Pirapora', 'PIRAPORA');
insert into risp (risp, city,city_fix) values('14ª RISP – Curvelo', 'Presidente Juscelino', 'PRESIDENTE JUSCELINO');
insert into risp (risp, city,city_fix) values('14ª RISP – Curvelo', 'Presidente Kubitschek', 'PRESIDENTE KUBITSCHEK');
insert into risp (risp, city,city_fix) values('14ª RISP – Curvelo', 'Santa Fé de Minas', 'SANTA FE DE MINAS');
insert into risp (risp, city,city_fix) values('14ª RISP – Curvelo', 'Santo Antônio do Itambé', 'SANTO ANTÔNIO DO ITAMBE');
insert into risp (risp, city,city_fix) values('14ª RISP – Curvelo', 'Santo Hipólito', 'SANTO HIPOLITO');
insert into risp (risp, city,city_fix) values('14ª RISP – Curvelo', 'São Gonçalo do Rio Preto', 'SAO GONCALO DO RIO PRETO');
insert into risp (risp, city,city_fix) values('14ª RISP – Curvelo', 'São Romão', 'SAO ROMAO');
insert into risp (risp, city,city_fix) values('14ª RISP – Curvelo', 'Senador Modestino Gonçalves', 'SENADOR MODESTINO GONCALVES');
insert into risp (risp, city,city_fix) values('14ª RISP – Curvelo', 'Serra Azul de Minas', 'SERRA AZUL DE MINAS');
insert into risp (risp, city,city_fix) values('14ª RISP – Curvelo', 'Serro', 'SERRO');
insert into risp (risp, city,city_fix) values('14ª RISP – Curvelo', 'Três Marias', 'TRES MARIAS');
insert into risp (risp, city,city_fix) values('14ª RISP – Curvelo', 'Turmalina', 'TURMALINA');
insert into risp (risp, city,city_fix) values('14ª RISP – Curvelo', 'Várzea da Palma', 'VARZEA DA PALMA');
insert into risp (risp, city,city_fix) values('14ª RISP – Curvelo', 'Veredinha', 'VEREDINHA');
insert into risp (risp, city,city_fix) values('15ª RISP – Teófilo Otoni', 'Águas Formosas', 'AGUAS FORMOSAS');
insert into risp (risp, city,city_fix) values('15ª RISP – Teófilo Otoni', 'Água Vermelhas', 'AGUA VERMELHAS');
insert into risp (risp, city,city_fix) values('15ª RISP – Teófilo Otoni', 'Almenara', 'ALMENARA');
insert into risp (risp, city,city_fix) values('15ª RISP – Teófilo Otoni', 'Aracuaí', 'ARACUAI');
insert into risp (risp, city,city_fix) values('15ª RISP – Teófilo Otoni', 'Ataleia', 'ATALEIA');
insert into risp (risp, city,city_fix) values('15ª RISP – Teófilo Otoni', 'Bandeira', 'BANDEIRA');
insert into risp (risp, city,city_fix) values('15ª RISP – Teófilo Otoni', 'Bertópolis', 'BERTOPOLIS');
insert into risp (risp, city,city_fix) values('15ª RISP – Teófilo Otoni', 'Cachoeira do Pajeú', 'CACHOEIRA DO PAJEU');
insert into risp (risp, city,city_fix) values('15ª RISP – Teófilo Otoni', 'Campanario', 'CAMPANARIO');
insert into risp (risp, city,city_fix) values('15ª RISP – Teófilo Otoni', 'Caraí', 'CARAI');
insert into risp (risp, city,city_fix) values('15ª RISP – Teófilo Otoni', 'Carlos Chagas', 'CARLOS CHAGAS');
insert into risp (risp, city,city_fix) values('15ª RISP – Teófilo Otoni', 'Catuji', 'CATUJI');
insert into risp (risp, city,city_fix) values('15ª RISP – Teófilo Otoni', 'Comercinho', 'COMERCINHO');
insert into risp (risp, city,city_fix) values('15ª RISP – Teófilo Otoni', 'Coronel Murta', 'CORONEL MURTA');
insert into risp (risp, city,city_fix) values('15ª RISP – Teófilo Otoni', 'Crisolita', 'CRISOLITA');
insert into risp (risp, city,city_fix) values('15ª RISP – Teófilo Otoni', 'Divisa Alegre', 'DIVISA ALEGRE');
insert into risp (risp, city,city_fix) values('15ª RISP – Teófilo Otoni', 'Divisópolis', 'DIVISOPOLIS');
insert into risp (risp, city,city_fix) values('15ª RISP – Teófilo Otoni', 'Felisburgo', 'FELISBURGO');
insert into risp (risp, city,city_fix) values('15ª RISP – Teófilo Otoni', 'Franciscópolis', 'FRANCISCOPOLIS');
insert into risp (risp, city,city_fix) values('15ª RISP – Teófilo Otoni', 'Frei Gaspar', 'FREI GASPAR');
insert into risp (risp, city,city_fix) values('15ª RISP – Teófilo Otoni', 'Fronteira dos Vales', 'FRONTEIRA DOS VALES');
insert into risp (risp, city,city_fix) values('15ª RISP – Teófilo Otoni', 'Itaipé', 'ITAIPE');
insert into risp (risp, city,city_fix) values('15ª RISP – Teófilo Otoni', 'Itambacuri', 'ITAMBACURI');
insert into risp (risp, city,city_fix) values('15ª RISP – Teófilo Otoni', 'Itaobim', 'ITAOBIM');
insert into risp (risp, city,city_fix) values('15ª RISP – Teófilo Otoni', 'Itinga', 'ITINGA');
insert into risp (risp, city,city_fix) values('15ª RISP – Teófilo Otoni', 'Jacinto', 'JACINTO');
insert into risp (risp, city,city_fix) values('15ª RISP – Teófilo Otoni', 'Jampruca', 'JAMPRUCA');
insert into risp (risp, city,city_fix) values('15ª RISP – Teófilo Otoni', 'Jequitinhonha', 'JEQUITINHONHA');
insert into risp (risp, city,city_fix) values('15ª RISP – Teófilo Otoni', 'Joaima', 'JOAIMA');
insert into risp (risp, city,city_fix) values('15ª RISP – Teófilo Otoni', 'Jordânia', 'JORDANIA');
insert into risp (risp, city,city_fix) values('15ª RISP – Teófilo Otoni', 'Ladainha', 'LADAINHA');
insert into risp (risp, city,city_fix) values('15ª RISP – Teófilo Otoni', 'Machacalis', 'MACHACALIS');
insert into risp (risp, city,city_fix) values('15ª RISP – Teófilo Otoni', 'Malacacheta', 'MALACACHETA');
insert into risp (risp, city,city_fix) values('15ª RISP – Teófilo Otoni', 'Mata Verde', 'MATA VERDE');
insert into risp (risp, city,city_fix) values('15ª RISP – Teófilo Otoni', 'Medina', 'MEDINA');
insert into risp (risp, city,city_fix) values('15ª RISP – Teófilo Otoni', 'Monte Formoso', 'MONTE FORMOSO');
insert into risp (risp, city,city_fix) values('15ª RISP – Teófilo Otoni', 'Nanuque', 'NANUQUE');
insert into risp (risp, city,city_fix) values('15ª RISP – Teófilo Otoni', 'Nova Modica', 'NOVA MODICA');
insert into risp (risp, city,city_fix) values('15ª RISP – Teófilo Otoni', 'Novo Cruzeiro', 'NOVO CRUZEIRO');
insert into risp (risp, city,city_fix) values('15ª RISP – Teófilo Otoni', 'Novo Oriente de Minas', 'NOVO ORIENTE DE MINAS');
insert into risp (risp, city,city_fix) values('15ª RISP – Teófilo Otoni', 'Ouro Verde de Minas', 'OURO VERDE DE MINAS');
insert into risp (risp, city,city_fix) values('15ª RISP – Teófilo Otoni', 'Padre Paraíso', 'PADRE PARAISO');
insert into risp (risp, city,city_fix) values('15ª RISP – Teófilo Otoni', 'Palmópolis', 'PALMOPOLIS');
insert into risp (risp, city,city_fix) values('15ª RISP – Teófilo Otoni', 'Pavão', 'PAVAO');
insert into risp (risp, city,city_fix) values('15ª RISP – Teófilo Otoni', 'Pedra Azul', 'PEDRA AZUL');
insert into risp (risp, city,city_fix) values('15ª RISP – Teófilo Otoni', 'Pescador', 'PESCADOR');
insert into risp (risp, city,city_fix) values('15ª RISP – Teófilo Otoni', 'Ponto dos Volantes', 'PONTO DOS VOLANTES');
insert into risp (risp, city,city_fix) values('15ª RISP – Teófilo Otoni', 'Pote', 'POTE');
insert into risp (risp, city,city_fix) values('15ª RISP – Teófilo Otoni', 'Rio do Prado', 'RIO DO PRADO');
insert into risp (risp, city,city_fix) values('15ª RISP – Teófilo Otoni', 'Rubim', 'RUBIM');
insert into risp (risp, city,city_fix) values('15ª RISP – Teófilo Otoni', 'Salto da Divisa', 'SALTO DA DIVISA');
insert into risp (risp, city,city_fix) values('15ª RISP – Teófilo Otoni', 'Santa Helena de Minas', 'SANTA HELENA DE MINAS');
insert into risp (risp, city,city_fix) values('15ª RISP – Teófilo Otoni', 'Santa Maria do Salto', 'SANTA MARIA DO SALTO');
insert into risp (risp, city,city_fix) values('15ª RISP – Teófilo Otoni', 'Santo Antônio do Jacinto', 'SANTO ANTÔNIO DO JACINTO');
insert into risp (risp, city,city_fix) values('15ª RISP – Teófilo Otoni', 'São José do Divino', 'SAO JOSE DO DIVINO');
insert into risp (risp, city,city_fix) values('15ª RISP – Teófilo Otoni', 'Serra dos Aimorés', 'SERRA DOS AIMORES');
insert into risp (risp, city,city_fix) values('15ª RISP – Teófilo Otoni', 'Setubinha', 'SETUBINHA');
insert into risp (risp, city,city_fix) values('15ª RISP – Teófilo Otoni', 'Teófilo Otoni', 'TEOFILO OTONI');
insert into risp (risp, city,city_fix) values('15ª RISP – Teófilo Otoni', 'Umburatiba', 'UMBURATIBA');
insert into risp (risp, city,city_fix) values('15ª RISP – Teófilo Otoni', 'Virgem da Lapa', 'VIRGEM DA LAPA');
insert into risp (risp, city,city_fix) values('16ª RISP – Unaí', 'Arinos', 'ARINOS');
insert into risp (risp, city,city_fix) values('16ª RISP – Unaí', 'Bonfinópolis de Minas', 'BONFINOPOLIS DE MINAS');
insert into risp (risp, city,city_fix) values('16ª RISP – Unaí', 'Brasilândia de Minas', 'BRASILANDIA DE MINAS');
insert into risp (risp, city,city_fix) values('16ª RISP – Unaí', 'Buritis', 'BURITIS');
insert into risp (risp, city,city_fix) values('16ª RISP – Unaí', 'Cabeceira Grande', 'CABECEIRA GRANDE');
insert into risp (risp, city,city_fix) values('16ª RISP – Unaí', 'Chapada Gaúcha', 'CHAPADA GAUCHA');
insert into risp (risp, city,city_fix) values('16ª RISP – Unaí', 'Dom Bosco', 'DOM BOSCO');
insert into risp (risp, city,city_fix) values('16ª RISP – Unaí', 'Formoso', 'FORMOSO');
insert into risp (risp, city,city_fix) values('16ª RISP – Unaí', 'Guarda Mor', 'GUARDA MOR');
insert into risp (risp, city,city_fix) values('16ª RISP – Unaí', 'João Pinheiro', 'JOAO PINHEIRO');
insert into risp (risp, city,city_fix) values('16ª RISP – Unaí', 'Natalândia', 'NATALANDIA');
insert into risp (risp, city,city_fix) values('16ª RISP – Unaí', 'Paracatu', 'PARACATU');
insert into risp (risp, city,city_fix) values('16ª RISP – Unaí', 'Riachinho', 'RIACHINHO');
insert into risp (risp, city,city_fix) values('16ª RISP – Unaí', 'Unaí', 'UNAI');
insert into risp (risp, city,city_fix) values('16ª RISP – Unaí', 'Uruana de Minas', 'URUANA DE MINAS');
insert into risp (risp, city,city_fix) values('16ª RISP – Unaí', 'Urucuia', 'URUCUIA');
insert into risp (risp, city,city_fix) values('16ª RISP – Unaí', 'Vazante', 'VAZANTE');
insert into risp (risp, city,city_fix) values('17ª RISP – Pouso Alegre', 'Aiuruoca', 'AIURUOCA');
insert into risp (risp, city,city_fix) values('17ª RISP – Pouso Alegre', 'Alagoa', 'ALAGOA');
insert into risp (risp, city,city_fix) values('17ª RISP – Pouso Alegre', 'Albertina', 'ALBERTINA');
insert into risp (risp, city,city_fix) values('17ª RISP – Pouso Alegre', 'Baependi', 'BAEPENDI');
insert into risp (risp, city,city_fix) values('17ª RISP – Pouso Alegre', 'Bocaina de Minas', 'BOCAINA DE MINAS');
insert into risp (risp, city,city_fix) values('17ª RISP – Pouso Alegre', 'Bom Repouso', 'BOM REPOUSO');
insert into risp (risp, city,city_fix) values('17ª RISP – Pouso Alegre', 'Borda da Mata', 'BORDA DA MATA');
insert into risp (risp, city,city_fix) values('17ª RISP – Pouso Alegre', 'Brasópolis', 'BRASOPOLIS');
insert into risp (risp, city,city_fix) values('17ª RISP – Pouso Alegre', 'Bueno Brandão', 'BUENO BRANDAO');
insert into risp (risp, city,city_fix) values('17ª RISP – Pouso Alegre', 'Cachoeira de Minas', 'CACHOEIRA DE MINAS');
insert into risp (risp, city,city_fix) values('17ª RISP – Pouso Alegre', 'Camanducaia', 'CAMANDUCAIA');
insert into risp (risp, city,city_fix) values('17ª RISP – Pouso Alegre', 'Cambuí', 'CAMBUI');
insert into risp (risp, city,city_fix) values('17ª RISP – Pouso Alegre', 'Careaçu', 'CAREACU');
insert into risp (risp, city,city_fix) values('17ª RISP – Pouso Alegre', 'Carmo de Minas', 'CARMO DE MINAS');
insert into risp (risp, city,city_fix) values('17ª RISP – Pouso Alegre', 'Carvalhos', 'CARVALHOS');
insert into risp (risp, city,city_fix) values('17ª RISP – Pouso Alegre', 'Caxambu', 'CAXAMBU');
insert into risp (risp, city,city_fix) values('17ª RISP – Pouso Alegre', 'Conceição das Pedras', 'CONCEICAO DAS PEDRAS');
insert into risp (risp, city,city_fix) values('17ª RISP – Pouso Alegre', 'Conceição dos Ouros', 'CONCEICAO DOS OUROS');
insert into risp (risp, city,city_fix) values('17ª RISP – Pouso Alegre', 'Congonhal', 'CONGONHAL');
insert into risp (risp, city,city_fix) values('17ª RISP – Pouso Alegre', 'Consolação', 'CONSOLACAO');
insert into risp (risp, city,city_fix) values('17ª RISP – Pouso Alegre', 'Cordislândia', 'CORDISLANDIA');
insert into risp (risp, city,city_fix) values('17ª RISP – Pouso Alegre', 'Córrego do Bom Jesus', 'CORREGO DO BOM JESUS');
insert into risp (risp, city,city_fix) values('17ª RISP – Pouso Alegre', 'Cristina', 'CRISTINA');
insert into risp (risp, city,city_fix) values('17ª RISP – Pouso Alegre', 'Cruzília', 'CRUZILIA');
insert into risp (risp, city,city_fix) values('17ª RISP – Pouso Alegre', 'Delfim Moreira', 'DELFIM MOREIRA');
insert into risp (risp, city,city_fix) values('17ª RISP – Pouso Alegre', 'Dom Viçoso', 'DOM VICOSO');
insert into risp (risp, city,city_fix) values('17ª RISP – Pouso Alegre', 'Espírito Santo do Dourado', 'ESPIRITO SANTO DO DOURADO');
insert into risp (risp, city,city_fix) values('17ª RISP – Pouso Alegre', 'Estiva', 'ESTIVA');
insert into risp (risp, city,city_fix) values('17ª RISP – Pouso Alegre', 'Extrema', 'EXTREMA');
insert into risp (risp, city,city_fix) values('17ª RISP – Pouso Alegre', 'Gonçalves', 'GONCALVES');
insert into risp (risp, city,city_fix) values('17ª RISP – Pouso Alegre', 'Heliodora', 'HELIODORA');
insert into risp (risp, city,city_fix) values('17ª RISP – Pouso Alegre', 'Inconfidentes', 'INCONFIDENTES');
insert into risp (risp, city,city_fix) values('17ª RISP – Pouso Alegre', 'Itajubá', 'ITAJUBA');
insert into risp (risp, city,city_fix) values('17ª RISP – Pouso Alegre', 'Itamonte', 'ITAMONTE');
insert into risp (risp, city,city_fix) values('17ª RISP – Pouso Alegre', 'Itanhandu', 'ITANHANDU');
insert into risp (risp, city,city_fix) values('17ª RISP – Pouso Alegre', 'Itapeva', 'ITAPEVA');
insert into risp (risp, city,city_fix) values('17ª RISP – Pouso Alegre', 'Jacutinga', 'JACUTINGA');
insert into risp (risp, city,city_fix) values('17ª RISP – Pouso Alegre', 'Liberdade', 'LIBERDADE');
insert into risp (risp, city,city_fix) values('17ª RISP – Pouso Alegre', 'Maria da Fé', 'MARIA DA FE');
insert into risp (risp, city,city_fix) values('17ª RISP – Pouso Alegre', 'Marmelópolis', 'MARMELOPOLIS');
insert into risp (risp, city,city_fix) values('17ª RISP – Pouso Alegre', 'Minduri', 'MINDURI');
insert into risp (risp, city,city_fix) values('17ª RISP – Pouso Alegre', 'Monte Sião', 'MONTE SIAO');
insert into risp (risp, city,city_fix) values('17ª RISP – Pouso Alegre', 'Munhoz', 'MUNHOZ');
insert into risp (risp, city,city_fix) values('17ª RISP – Pouso Alegre', 'Natércia', 'NATERCIA');
insert into risp (risp, city,city_fix) values('17ª RISP – Pouso Alegre', 'Ouro Fino', 'OURO FINO');
insert into risp (risp, city,city_fix) values('17ª RISP – Pouso Alegre', 'Paraisópolis', 'PARAISOPOLIS');
insert into risp (risp, city,city_fix) values('17ª RISP – Pouso Alegre', 'Passa Quatro', 'PASSA QUATRO');
insert into risp (risp, city,city_fix) values('17ª RISP – Pouso Alegre', 'Passa Vinte', 'PASSA VINTE');
insert into risp (risp, city,city_fix) values('17ª RISP – Pouso Alegre', 'Pedralva', 'PEDRALVA');
insert into risp (risp, city,city_fix) values('17ª RISP – Pouso Alegre', 'Piranguçu', 'PIRANGUCU');
insert into risp (risp, city,city_fix) values('17ª RISP – Pouso Alegre', 'Piranguinho', 'PIRANGUINHO');
insert into risp (risp, city,city_fix) values('17ª RISP – Pouso Alegre', 'Pouso Alegre', 'POUSO ALEGRE');
insert into risp (risp, city,city_fix) values('17ª RISP – Pouso Alegre', 'Pouso Alto', 'POUSO ALTO');
insert into risp (risp, city,city_fix) values('17ª RISP – Pouso Alegre', 'Santa Rita do Sapucaí', 'SANTA RITA DO SAPUCAI');
insert into risp (risp, city,city_fix) values('17ª RISP – Pouso Alegre', 'São Gonçalo do Sapucaí', 'SAO GONCALO DO SAPUCAI');
insert into risp (risp, city,city_fix) values('17ª RISP – Pouso Alegre', 'São João da Mata', 'SAO JOAO DA MATA');
insert into risp (risp, city,city_fix) values('17ª RISP – Pouso Alegre', 'São José do Alegre', 'SAO JOSE DO ALEGRE');
insert into risp (risp, city,city_fix) values('17ª RISP – Pouso Alegre', 'São Lourenço', 'SAO LOURENCO');
insert into risp (risp, city,city_fix) values('17ª RISP – Pouso Alegre', 'São Sebastião da Bela Vista', 'SAO SEBASTIAO DA BELA VISTA');
insert into risp (risp, city,city_fix) values('17ª RISP – Pouso Alegre', 'São Sebastião do Rio Verde', 'SAO SEBASTIAO DO RIO VERDE');
insert into risp (risp, city,city_fix) values('17ª RISP – Pouso Alegre', 'Sapucaí Mirim', 'SAPUCAI MIRIM');
insert into risp (risp, city,city_fix) values('17ª RISP – Pouso Alegre', 'Senador Amaral', 'SENADOR AMARAL');
insert into risp (risp, city,city_fix) values('17ª RISP – Pouso Alegre', 'Senador José Bento', 'SENADOR JOSE BENTO');
insert into risp (risp, city,city_fix) values('17ª RISP – Pouso Alegre', 'Seritinga', 'SERITINGA');
insert into risp (risp, city,city_fix) values('17ª RISP – Pouso Alegre', 'Serranos', 'SERRANOS');
insert into risp (risp, city,city_fix) values('17ª RISP – Pouso Alegre', 'Silvianópolis', 'SILVIANOPOLIS');
insert into risp (risp, city,city_fix) values('17ª RISP – Pouso Alegre', 'Soledade de Minas', 'SOLEDADE DE MINAS');
insert into risp (risp, city,city_fix) values('17ª RISP – Pouso Alegre', 'Tocos do Moji', 'TOCOS DO MOJI');
insert into risp (risp, city,city_fix) values('17ª RISP – Pouso Alegre', 'Toledo', 'TOLEDO');
insert into risp (risp, city,city_fix) values('17ª RISP – Pouso Alegre', 'Turvolândia', 'TURVOLANDIA');
insert into risp (risp, city,city_fix) values('17ª RISP – Pouso Alegre', 'Virgínia', 'VIRGINIA');
insert into risp (risp, city,city_fix) values('17ª RISP – Pouso Alegre', 'Wenceslau Brás', 'WENCESLAU BRAS');
insert into risp (risp, city,city_fix) values('18ª RISP – Poços de Caldas', 'Alfenas', 'ALFENAS');
insert into risp (risp, city,city_fix) values('18ª RISP – Poços de Caldas', 'Alpinópolis', 'ALPINOPOLIS');
insert into risp (risp, city,city_fix) values('18ª RISP – Poços de Caldas', 'Alterosa', 'ALTEROSA');
insert into risp (risp, city,city_fix) values('18ª RISP – Poços de Caldas', 'Andradas', 'ANDRADAS');
insert into risp (risp, city,city_fix) values('18ª RISP – Poços de Caldas', 'Arceburgo', 'ARCEBURGO');
insert into risp (risp, city,city_fix) values('18ª RISP – Poços de Caldas', 'Areado', 'AREADO');
insert into risp (risp, city,city_fix) values('18ª RISP – Poços de Caldas', 'Bandeira do Sul', 'BANDEIRA DO SUL');
insert into risp (risp, city,city_fix) values('18ª RISP – Poços de Caldas', 'Bom Jesus da Penha', 'BOM JESUS DA PENHA');
insert into risp (risp, city,city_fix) values('18ª RISP – Poços de Caldas', 'Botelhos', 'BOTELHOS');
insert into risp (risp, city,city_fix) values('18ª RISP – Poços de Caldas', 'Cabo Verde', 'CABO VERDE');
insert into risp (risp, city,city_fix) values('18ª RISP – Poços de Caldas', 'Caldas', 'CALDAS');
insert into risp (risp, city,city_fix) values('18ª RISP – Poços de Caldas', 'Campestre', 'CAMPESTRE');
insert into risp (risp, city,city_fix) values('18ª RISP – Poços de Caldas', 'Campo do Meio', 'CAMPO DO MEIO');
insert into risp (risp, city,city_fix) values('18ª RISP – Poços de Caldas', 'Campos Gerais', 'CAMPOS GERAIS');
insert into risp (risp, city,city_fix) values('18ª RISP – Poços de Caldas', 'Capetinga', 'CAPETINGA');
insert into risp (risp, city,city_fix) values('18ª RISP – Poços de Caldas', 'Capitólio', 'CAPITOLIO');
insert into risp (risp, city,city_fix) values('18ª RISP – Poços de Caldas', 'Carmo do Rio Claro', 'CARMO DO RIO CLARO');
insert into risp (risp, city,city_fix) values('18ª RISP – Poços de Caldas', 'Carvalhópolis', 'CARVALHOPOLIS');
insert into risp (risp, city,city_fix) values('18ª RISP – Poços de Caldas', 'Cássia', 'CASSIA');
insert into risp (risp, city,city_fix) values('18ª RISP – Poços de Caldas', 'Claraval', 'CLARAVAL');
insert into risp (risp, city,city_fix) values('18ª RISP – Poços de Caldas', 'Conceição da Aparecida', 'CONCEICAO DA APARECIDA');
insert into risp (risp, city,city_fix) values('18ª RISP – Poços de Caldas', 'Delfinópolis', 'DELFINOPOLIS');
insert into risp (risp, city,city_fix) values('18ª RISP – Poços de Caldas', 'Divisa Nova', 'DIVISA NOVA');
insert into risp (risp, city,city_fix) values('18ª RISP – Poços de Caldas', 'Doresópolis', 'DORESOPOLIS');
insert into risp (risp, city,city_fix) values('18ª RISP – Poços de Caldas', 'Fama', 'FAMA');
insert into risp (risp, city,city_fix) values('18ª RISP – Poços de Caldas', 'Fortaleza de Minas', 'FORTALEZA DE MINAS');
insert into risp (risp, city,city_fix) values('18ª RISP – Poços de Caldas', 'Guaranésia', 'GUARANESIA');
insert into risp (risp, city,city_fix) values('18ª RISP – Poços de Caldas', 'Guaxupé', 'GUAXUPE');
insert into risp (risp, city,city_fix) values('18ª RISP – Poços de Caldas', 'Ibiraci', 'IBIRACI');
insert into risp (risp, city,city_fix) values('18ª RISP – Poços de Caldas', 'Ibitura de Minas', 'IBITURA DE MINAS');
insert into risp (risp, city,city_fix) values('18ª RISP – Poços de Caldas', 'Ipuiuna', 'IPUIUNA');
insert into risp (risp, city,city_fix) values('18ª RISP – Poços de Caldas', 'Itamogi', 'ITAMOGI');
insert into risp (risp, city,city_fix) values('18ª RISP – Poços de Caldas', 'Itaú de Minas', 'ITAU DE MINAS');
insert into risp (risp, city,city_fix) values('18ª RISP – Poços de Caldas', 'Jacuí', 'JACUI');
insert into risp (risp, city,city_fix) values('18ª RISP – Poços de Caldas', 'Juruaia', 'JURUAIA');
insert into risp (risp, city,city_fix) values('18ª RISP – Poços de Caldas', 'Machado', 'MACHADO');
insert into risp (risp, city,city_fix) values('18ª RISP – Poços de Caldas', 'Monte Belo', 'MONTE BELO');
insert into risp (risp, city,city_fix) values('18ª RISP – Poços de Caldas', 'Monte Santo de Minas', 'MONTE SANTO DE MINAS');
insert into risp (risp, city,city_fix) values('18ª RISP – Poços de Caldas', 'Muzambinho', 'MUZAMBINHO');
insert into risp (risp, city,city_fix) values('18ª RISP – Poços de Caldas', 'Nova Resende', 'NOVA RESENDE');
insert into risp (risp, city,city_fix) values('18ª RISP – Poços de Caldas', 'Paraguaçu', 'PARAGUACU');
insert into risp (risp, city,city_fix) values('18ª RISP – Poços de Caldas', 'Passos', 'PASSOS');
insert into risp (risp, city,city_fix) values('18ª RISP – Poços de Caldas', 'Piumhi', 'PIUMHI');
insert into risp (risp, city,city_fix) values('18ª RISP – Poços de Caldas', 'Poço Fundo', 'POCO FUNDO');
insert into risp (risp, city,city_fix) values('18ª RISP – Poços de Caldas', 'Poços de Caldas', 'POCOS DE CALDAS');
insert into risp (risp, city,city_fix) values('18ª RISP – Poços de Caldas', 'Pratapólis', 'PRATAPOLIS');
insert into risp (risp, city,city_fix) values('18ª RISP – Poços de Caldas', 'Santa Rita de Caldas', 'SANTA RITA DE CALDAS');
insert into risp (risp, city,city_fix) values('18ª RISP – Poços de Caldas', 'São João Batista do Glória', 'SAO JOAO BATISTA DO GLORIA');
insert into risp (risp, city,city_fix) values('18ª RISP – Poços de Caldas', 'São José da Barra', 'SAO JOSE DA BARRA');
insert into risp (risp, city,city_fix) values('18ª RISP – Poços de Caldas', 'São Pedro da União', 'SAO PEDRO DA UNIAO');
insert into risp (risp, city,city_fix) values('18ª RISP – Poços de Caldas', 'São Roque de Minas', 'SAO ROQUE DE MINAS');
insert into risp (risp, city,city_fix) values('18ª RISP – Poços de Caldas', 'São Sebastião do Paraíso', 'SAO SEBASTIAO DO PARAISO');
insert into risp (risp, city,city_fix) values('18ª RISP – Poços de Caldas', 'São Tomás de Aquino', 'SAO TOMAS DE AQUINO');
insert into risp (risp, city,city_fix) values('18ª RISP – Poços de Caldas', 'Serrania', 'SERRANIA');
insert into risp (risp, city,city_fix) values('18ª RISP – Poços de Caldas', 'Vargem Bonita', 'VARGEM BONITA');
insert into risp (risp, city,city_fix) values('19ª RISP - Sete Lagoas', 'Sete Lagoas', 'SETE LAGOAS');
insert into risp (risp, city,city_fix) values('19ª RISP - Sete Lagoas', 'Santana de Pirapama', 'SANTANA DE PIRAPAMA');
insert into risp (risp, city,city_fix) values('19ª RISP - Sete Lagoas', 'Cordisburgo', 'CORDISBURGO');
insert into risp (risp, city,city_fix) values('19ª RISP - Sete Lagoas', 'Paraopeba', 'PARAOPEBA');
insert into risp (risp, city,city_fix) values('19ª RISP - Sete Lagoas', 'Araçaí', 'ARACAI');
insert into risp (risp, city,city_fix) values('19ª RISP - Sete Lagoas', 'Jequitibá', 'JEQUITIBA');
insert into risp (risp, city,city_fix) values('19ª RISP - Sete Lagoas', 'Baldim', 'BALDIM');
insert into risp (risp, city,city_fix) values('19ª RISP - Sete Lagoas', 'Caetanópolis', 'CAETANOPOLIS');
insert into risp (risp, city,city_fix) values('19ª RISP - Sete Lagoas', 'Funilândia', 'FUNILANDIA');
insert into risp (risp, city,city_fix) values('19ª RISP - Sete Lagoas', 'Inhaúma', 'INHAUMA');
insert into risp (risp, city,city_fix) values('19ª RISP - Sete Lagoas', 'Cachoeira da Prata', 'CACHOEIRA DA PRATA');
insert into risp (risp, city,city_fix) values('19ª RISP - Sete Lagoas', 'Fortuna de Minas', 'FORTUNA DE MINAS');
insert into risp (risp, city,city_fix) values('19ª RISP - Sete Lagoas', 'Prudente de Morais', 'PRUDENTE DE MORAIS');
insert into risp (risp, city,city_fix) values('19ª RISP - Sete Lagoas', 'Matozinhos', 'MATOZINHOS');
insert into risp (risp, city,city_fix) values('19ª RISP - Sete Lagoas', 'Capim Branco', 'CAPIM BRANCO');
insert into risp (risp, city,city_fix) values('19ª RISP - Sete Lagoas', 'Pedro Leopoldo', 'PEDRO LEOPOLDO');
insert into risp (risp, city,city_fix) values('socioeducativo', 'Santa Luzia', 'SANTA LUZIA');
insert into risp (risp, city,city_fix) values('socioeducativo', 'Pirapora', 'PIRAPORA');
insert into risp (risp, city,city_fix) values('socioeducativo', 'Montes Claros', 'MONTES CLAROS');
insert into risp (risp, city,city_fix) values('socioeducativo', 'Uberlândia', 'UBERLANDIA');
insert into risp (risp, city,city_fix) values('socioeducativo', 'Belo Horizonte', 'BELO HORIZONTE');
insert into risp (risp, city,city_fix) values('socioeducativo', 'Unaí', 'UNAI');
insert into risp (risp, city,city_fix) values('socioeducativo', 'Teófilo Otoni', 'TEOFILO OTONI');
insert into risp (risp, city,city_fix) values('socioeducativo', 'Sete Lagoas', 'SETE LAGOAS');
insert into risp (risp, city,city_fix) values('socioeducativo', 'Contagem', 'CONTAGEM');
insert into risp (risp, city,city_fix) values('socioeducativo', 'Governador Valadares', 'GOVERNADOR VALADARES');
insert into risp (risp, city,city_fix) values('socioeducativo', 'Uberaba', 'UBERABA');
insert into risp (risp, city,city_fix) values('socioeducativo', 'Patos de Minas ', 'PATOS DE MINAS');
insert into risp (risp, city,city_fix) values('socioeducativo', 'Divinópolis', 'DIVINOPOLIS');
insert into risp (risp, city,city_fix) values('socioeducativo', 'Juiz de Fora', 'JUIZ DE FORA');
insert into risp (risp, city,city_fix) values('socioeducativo', 'Ipatinga', 'IPATINGA');
insert into risp (risp, city,city_fix) values('socioeducativo', 'Ribeirão das Neves', 'RIBEIRAO DAS NEVES');