CREATE DATABASE vendas_sucos;

CREATE DATABASE vendas_sucos2 DEFAULT CHARACTER SET utf8;

CREATE DATABASE IF NOT EXISTS vendas_sucos2;

DROP DATABASE IF EXISTS vendas_sucos2;

USE vendas_sucos;

CREATE TABLE produtos(
CODIGO VARCHAR(10) NOT NULL,
DESCRITOR VARCHAR (100) NULL,
SABOR VARCHAR(50) NULL,
TAMANHO VARCHAR(50) NULL,
EMBALAGEM VARCHAR(50) NULL,
PRECO_LISTA FLOAT NULL,
PRIMARY KEY(CODIGO));

CREATE TABLE VENDEDORES(
MATRICULA VARCHAR(5) NOT NULL,
NOME VARCHAR(100) NULL,
BAIRRO VARCHAR(50) NULL,
COMISSOA FLOAT NULL,
DATA_ADIMISSAO DATE NULL,
FERIAS BIT(1),
PRIMARY KEY(MATRICULA));

ALTER TABLE VENDEDORES RENAME COLUMN DATA_ADIMISSAO TO DATA_ADMISSAO;
#ALTERAR O NOME DE COLUNAS PK É COMPLICADO, SENDO MELHOR REFAZER A COLUNA COM O NOME CORRETO, A FUNÇÃO RENAME É RECENTE (WORKBENCH 8.0)

CREATE TABLE IF NOT EXISTS CLIENTES(
CPF VARCHAR(11) NOT NULL,
NOME VARCHAR(100) DEFAULT NULL,
ENDERECO VARCHAR(150) DEFAULT NULL,
BAIRRO VARCHAR(50) DEFAULT NULL,
CIDADE VARCHAR(50) DEFAULT NULL,
ESTADO VARCHAR(50) DEFAULT NULL,
CEP VARCHAR(8) DEFAULT NULL,
DATA_NASCIMENTO DATE DEFAULT NULL,
IDADE INT DEFAULT NULL,
SEXO VARCHAR(1) DEFAULT NULL,
LIMITE_CREDITO FLOAT DEFAULT NULL,
VOLUME_COMPRA FLOAT DEFAULT NULL,
PRIMEIRA_COMPRA BIT(1) DEFAULT NULL,
PRIMARY KEY(CPF));

CREATE TABLE IF NOT EXISTS NOTAS(
NUMERO VARCHAR(5) NOT NULL,
DATA_VENDA DATE NULL,
CPF VARCHAR (11) NULL,
MATRICULA VARCHAR(5) NULL,
IMPOSTO FLOAT NULL,
PRIMARY KEY(NUMERO));

CREATE TABLE ITENS_NOTAS(
NUMERO VARCHAR (5) NOT NULL,
CODIGO VARCHAR (10) NOT NULL,
QUANTIDADE INT NULL,
PRECO FLOAT,
PRIMARY KEY(NUMERO, CODIGO));

#CRIAÇÃO DA SFOREIGN KEYS

ALTER TABLE NOTAS ADD CONSTRAINT FK_CLIENTES FOREIGN KEY (CPF) REFERENCES CLIENTES(CPF);

ALTER TABLE NOTAS ADD CONSTRAINT FK_VENDEDORES FOREIGN KEY (MATRICULA) REFERENCES VENDEDORES(MATRICULA);

ALTER TABLE ITENS_NOTAS ADD CONSTRAINT FK_PRODUTOS FOREIGN KEY (CODIGO) REFERENCES PRODUTOS(CODIGO);

ALTER TABLE ITENS_NOTAS ADD CONSTRAINT FK_NOTAS FOREIGN KEY (NUMERO) REFERENCES NOTAS(NUMERO);

ALTER TABLE TABELA_DE_VENDAS RENAME NOTAS;
