use vendas_sucos;

CREATE TABLE tb_id (ID INT AUTO_INCREMENT, DESCRITOR VARCHAR (20), PRIMARY KEY (ID));

insert into tb_id (DESCRITOR) values('Cliente1');
SELECT * FROM tb_id;
insert into tb_id (DESCRITOR) values('Cliente2');
insert into tb_id (DESCRITOR) values('Cliente3');
insert into tb_id (id, DESCRITOR) values(null, 'Cliente4');
insert into tb_id (DESCRITOR) values('Cliente6');

DELETE FROM TB_ID WHERE ID = 5;

insert into tb_id (id, DESCRITOR) values(NULL, 'Cliente8');

CREATE TABLE tb_padrao(
ID INT AUTO_INCREMENT, 
DESCRITOR VARCHAR(20), 
ENDERECO VARCHAR(100) NULL, 
CIDADE VARCHAR(50) DEFAULT 'Rio de Janeiro',
DATA_CRIACAO timestamp DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (ID));

INSERT INTO TB_PADRAO(DESCRITOR, ENDERECO, CIDADE, DATA_CRIACAO)
VALUES('CLIENTE X', 'RUA PROJETADA', 'SÃO PAULO', '2019-01-01');

SELECT * FROM TB_PADRAO;

INSERT INTO TB_PADRAO(DESCRITOR) VALUES ('CLIENTE Y');

CREATE TABLE tb_faturamento (DATA_VENDA DATE NULL, TOTAL_VENDA FLOAT);

SELECT * FROM TB_FATURAMENTO;

SELECT * FROM NOTAS;

SELECT * FROM ITENS_NOTAS;

INSERT INTO NOTAS(NUMERO, DATA_VENDA, CPF, MATRICULA, IMPOSTO) 
VALUES('0102', '2019-05-08', '1471156710', '235', '0.1'); 
INSERT INTO itens_notas(NUMERO, CODIGO, QUANTIDADE, PRECO)
VALUES('0102','1000889', 100, 10);
INSERT INTO itens_notas(NUMERO, CODIGO, QUANTIDADE, PRECO)
VALUES('0102','1002334', 100, 10);

DELETE FROM TB_FATURAMENTO;
INSERT INTO TB_FATURAMENTO
SELECT A.DATA_VENDA, SUM(B.QUANTIDADE * B.PRECO) AS TOTAL_VENDA FROM  NOTAS A INNER JOIN ITENS_NOTAS B ON A.NUMERO = B.NUMERO
GROUP BY DATA_VENDA;
SELECT * FROM TB_FATURAMENTO;

DELIMITER //
CREATE TRIGGER TG_FATURAMENTO_INSERT AFTER INSERT ON ITENS_NOTAS
FOR EACH ROW BEGIN
		DELETE FROM TB_FATURAMENTO;
		INSERT INTO TB_FATURAMENTO
		SELECT A.DATA_VENDA, SUM(B.QUANTIDADE * B.PRECO) AS TOTAL_VENDA FROM  NOTAS A INNER JOIN ITENS_NOTAS B ON A.NUMERO = B.NUMERO
		GROUP BY DATA_VENDA;
END //

DELIMITER //
CREATE TRIGGER TG_CLIENTES_IDADE_INSERT AFTER INSERT ON CLIENTES
FOR EACH ROW 
BEGIN
        INSERT INTO CLIENTES(IDADE) VALUES( ROUND(current_timestamp() - DATA_NASCIMENTO));
END      //

DELIMITER //
CREATE TRIGGER TG_CLIENTES_IDADE_INSERT BEFORE INSERT ON CLIENTES
FOR EACH ROW 
BEGIN
        SET NEW.IDADE = TIMESTAMPFDIFF(YEAR, NEW.DATA_NASCIMENTO, NOW());
END      //

SELECT * FROM NOTAS;
SELECT * FROM ITENS_NOTAS;

SELECT * FROM TB_FATURAMENTO;

UPDATE ITENS_NOTAS SET QUANTIDADE = 200 WHERE NUMERO = '0104' AND CODIGO = '1002334';

DELETE FROM ITENS_NOTAS WHERE NUMERO = '0104' AND CODIGO = '1002334';

DELIMITER //
CREATE TRIGGER TG_FATURAMENTO_UPDATE AFTER UPDATE ON ITENS_NOTAS
FOR EACH ROW BEGIN
		DELETE FROM TB_FATURAMENTO;
		INSERT INTO TB_FATURAMENTO
		SELECT A.DATA_VENDA, SUM(B.QUANTIDADE * B.PRECO) AS TOTAL_VENDA FROM  NOTAS A INNER JOIN ITENS_NOTAS B ON A.NUMERO = B.NUMERO
		GROUP BY DATA_VENDA;
END //

DELIMITER //
CREATE TRIGGER TG_FATURAMENTO_DELETE AFTER DELETE ON ITENS_NOTAS
FOR EACH ROW BEGIN
		DELETE FROM TB_FATURAMENTO;
		INSERT INTO TB_FATURAMENTO
		SELECT A.DATA_VENDA, SUM(B.QUANTIDADE * B.PRECO) AS TOTAL_VENDA FROM  NOTAS A INNER JOIN ITENS_NOTAS B ON A.NUMERO = B.NUMERO
		GROUP BY DATA_VENDA;
END //