SELECT DISTINCT BAIRRO FROM tabela_de_clientes WHERE CIDADE = 'RIO DE JANEIRO';

SELECT * FROM tabela_de_produtos LIMIT 5;

#Pegar a partir do segundo, não incluso, os próximos 3
SELECT * FROM tabela_de_produtos LIMIT 2,3;

SELECT * FROM notas_fiscais WHERE DATA_VENDA ='2017-01-01' LIMIT 10;

SELECT * FROM tabela_de_produtos;

SELECT * FROM tabela_de_produtos ORDER BY PRECO_DE_LISTA;

SELECT * FROM tabela_de_produtos ORDER BY PRECO_DE_LISTA DESC;

SELECT * FROM tabela_de_produtos ORDER BY NOME_DO_PRODUTO DESC;

SELECT * FROM tabela_de_produtos ORDER BY EMBALAGEM, NOME_DO_PRODUTO;

SELECT * FROM tabela_de_produtos WHERE NOME_DO_PRODUTO = 'Linha Refrescante - 1 Litro - Morango/Limão';
SELECT * FROM itens_notas_fiscais WHERE CODIGO_DO_PRODUTO = '1101035' ORDER BY QUANTIDADE DESC;

SELECT * FROM tabela_de_produtos A INNER JOIN itens_notas_fiscais B ON A.CODIGO_DO_PRODUTO = B.CODIGO_DO_PRODUTO
WHERE A.NOME_DO_PRODUTO = 'Linha Refrescante - 1 Litro - Morango/Limão'
ORDER BY B.QUANTIDADE DESC ;

SELECT ESTADO, LIMITE_DE_CREDITO FROM tabela_de_clientes;

SELECT ESTADO, SUM(LIMITE_DE_CREDITO) AS LIMITE FROM tabela_de_clientes GROUP BY ESTADO;

SELECT EMBALAGEM, PRECO_DE_LISTA FROM tabela_de_produtos;

SELECT EMBALAGEM, MAX(PRECO_DE_LISTA) FROM tabela_de_produtos GROUP BY EMBALAGEM;

SELECT EMBALAGEM, COUNT(*) AS CONTADOR FROM tabela_de_produtos GROUP BY EMBALAGEM;

SELECT BAIRRO, SUM(LIMITE_DE_CREDITO) FROM tabela_de_clientes GROUP BY BAIRRO;

SELECT ESTADO, BAIRRO, SUM(LIMITE_DE_CREDITO) FROM tabela_de_clientes WHERE CIDADE = 'Rio de Janeiro' GROUP BY ESTADO, BAIRRO;

SELECT NOME_DO_PRODUTO, COUNT(*) FROM tabela_de_produtos A INNER JOIN itens_notas_fiscais B ON A.CODIGO_DO_PRODUTO = B.CODIGO_DO_PRODUTO
WHERE A.NOME_DO_PRODUTO = 'Linha Refrescante - 1 Litro - Morango/Limão' AND B.QUANTIDADE = 99
GROUP BY NOME_DO_PRODUTO
ORDER BY B.QUANTIDADE DESC ;

SELECT ESTADO, SUM(LIMITE_DE_CREDITO) AS SOMA_LIMITE FROM tabela_de_clientes WHERE SOMA_LIMITE > 900000 GROUP BY ESTADO;

SELECT ESTADO, SUM(LIMITE_DE_CREDITO) AS SOMA_LIMITE FROM tabela_de_clientes GROUP BY ESTADO HAVING SUM(LIMITE_DE_CREDITO) > 900000;

SELECT EMBALAGEM, MAX(PRECO_DE_LISTA) AS MAIOR_PRECO, MIN(PRECO_DE_LISTA) AS MENOR_PRECO FROM tabela_de_produtos GROUP BY EMBALAGEM
HAVING SUM(PRECO_DE_LISTA) <= 80 AND MAX(PRECO_DE_LISTA) >= 5;

SELECT A.CPF, B.NOME, COUNT(*) AS COMPRAS from notas_fiscais A INNER JOIN tabela_de_clientes B ON A.CPF = B.CPF
WHERE YEAR(DATA_VENDA) = 2016
GROUP BY B.CPF, B.NOME HAVING COUNT(NUMERO) > 2000;

SELECT CPF, COUNT(*) FROM notas_fiscais WHERE YEAR(DATA_VENDA) = 2016 GROUP BY CPF HAVING COUNT(*) > 2000;

SELECT EMBALAGEM,
CASE WHEN PRECO_DE_LISTA >= 12 THEN 'PRODUTO CARO'
	 WHEN PRECO_DE_LISTA >= 7 THEN 'PRODUTO EM CONTA'
     ELSE 'PRODUTO BARATO' END AS STATUS_PRECO, AVG(PRECO_DE_LISTA) AS PRECO_MEDIO
 FROM tabela_de_produtos
 GROUP BY EMBALAGEM, CASE WHEN PRECO_DE_LISTA >= 12 THEN 'PRODUTO CARO'
	 WHEN PRECO_DE_LISTA >= 7 THEN 'PRODUTO EM CONTA'
     ELSE 'PRODUTO BARATO' END;
     
SELECT NOME, CASE 
	WHEN YEAR(DATA_DE_NASCIMENTO)<1990 THEN 'VELHOS' 
	WHEN YEAR(DATA_DE_NASCIMENTO)<1995 THEN 'JOVENS' 
    ELSE 'CRIANÇAS' END AS CATEGORIA FROM tabela_de_clientes;